#!/usr/bin/env python3
"""Generate German (DE) translations for all missing keys."""
import json, os

BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'src/lib/i18n/locales')

def set_nested(obj, dotpath, value):
    parts = dotpath.split('.')
    for part in parts[:-1]:
        if part not in obj: obj[part] = {}
        obj = obj[part]
    obj[parts[-1]] = value

with open(os.path.join(BASE, 'de.json'), 'r') as f:
    locale = json.load(f)

t = {
    "email.generateNew": "Neu Generieren",
    "email.changeDomain": "Domain Ändern",
    "email.refreshPage": "Seite Aktualisieren",
    "email.generateCustomEmail": "Benutzerdefinierte E-Mail Generieren",
    "email.waitingForEmails": "Warte auf eingehende E-Mails",
    "email.refreshStopped": "Automatische Aktualisierung gestoppt",
    "email.inboxEmpty": "Dein Posteingang ist leer",
    "email.domain": "Domain",
    "email.gmail": "Gmail",
    "email.googlemail": "GoogleMail",
    "email.copyToClipboard": "In die Zwischenablage kopieren",
    "email.useCustomAlias2": "Benutzerdefinierten Alias verwenden",
    "email.changeDomain2": "Domain ändern",
    "email.refreshPage2": "Seite aktualisieren",
    "email.scenario": "Szenario:",
    "email.solution": "Lösung:",
    "email.challenge": "Herausforderung:",
    "email.testingWorkflow": "Testworkflow:",
    "email.testScenarios": "Testszenarien:",
    "email.perfectFor": "Perfekt für:",
    "email.important": "WICHTIG:",
    "email.neverUse": "Verwende NIEMALS temporäre E-Mails für:",
    "emailGeneratorPage.h1": "Fire Temp Mail – Dein Kostenloser Wegwerf-E-Mail-Generator",
    "emailGeneratorPage.lead": "Generiere sofort eine Wegwerf-E-Mail-Adresse. Halte deine echte E-Mail privat und deinen Posteingang frei von unerwünschten Nachrichten und Spam.",
    "emailGeneratorPage.seoTitle": "E-Mail-Generator für Entwickler und QA-Tests",
    "emailGeneratorPage.seoDesc": "Professioneller temporärer E-Mail-Generator, speziell für Softwareentwickler, QA-Ingenieure und Automatisierungstester entwickelt. Generiere unbegrenzt Wegwerf-E-Mail-Adressen zum Testen von Registrierungsabläufen, E-Mail-Verifizierungssystemen, Passwort-Zurücksetzungen und Benachrichtigungslogik — ohne Testkonten zu verwalten oder persönliche Posteingänge zu füllen.",
    "emailGeneratorPage.whyTitle": "Warum Entwickler Wegwerf-E-Mails zum Testen Brauchen",
    "emailGeneratorPage.whyP1": "Das Testen von E-Mail-abhängigen Funktionen ist unverzichtbar, aber mühsam. Du musst Benutzerregistrierung, Bestätigungslinks, Passwort-Zurücksetzungsabläufe und Benachrichtigungssysteme überprüfen — aber das Erstellen dutzender echter E-Mail-Konten ist langsam, nicht nachhaltig und füllt deinen Posteingang.",
    "emailGeneratorPage.whyP2": "Fire Temp Mail bietet sofortige Wegwerf-E-Mail-Adressen, die speziell für Softwaretests entwickelt wurden. Generiere unbegrenzt temporäre E-Mails, um die E-Mail-Abläufe deiner Anwendung zu testen, ohne Testkonten zu verwalten oder mit E-Mail-Anbieter-Beschränkungen zu kämpfen.",
    "emailGeneratorPage.painPointsTitle": "Häufige Entwicklerprobleme (Gelöst)",
    "emailGeneratorPage.pp1": "Manuelles Erstellen von Gmail/Outlook-Testkonten → Generiere sofort unbegrenzte E-Mails",
    "emailGeneratorPage.pp2": "Verwaltung von Passwörtern für mehrere Testkonten → Keine Anmeldedaten nötig",
    "emailGeneratorPage.pp3": "Alte Testdaten aufräumen → Automatische Löschung nach 24 Stunden",
    "emailGeneratorPage.pp4": "E-Mail-Anbieter blockieren automatisierte Registrierungen → Echte Domains, die überall funktionieren",
    "emailGeneratorPage.pp5": "Multi-User-Szenarien testen → Unbegrenzte einzigartige Adressen auf Abruf",
    "emailGeneratorPage.pp6": "CI/CD-Pipelines brauchen frische E-Mails → Generierung ohne Setup",
    "emailGeneratorPage.uc1Title": "1. Benutzerregistrierung und E-Mail-Verifizierung Testen",
    "emailGeneratorPage.uc1P1": "Deine Anwendung erfordert E-Mail-Verifizierung bei der Registrierung. Du musst testen, dass Verifizierungs-E-Mails ankommen, Links korrekt funktionieren, Token ordnungsgemäß ablaufen und Randfälle behandelt werden.",
    "emailGeneratorPage.uc1P2": "Generiere eine temporäre E-Mail → Registriere dich in deiner App → Überprüfe den Posteingang auf die Verifizierungs-E-Mail (kommt in Sekunden an) → Extrahiere den Verifizierungslink/-token → Schließe die Verifizierung ab → Teste Randfälle (abgelaufene Token, doppelte Verifizierungen).",
    "emailGeneratorPage.uc2Title": "2. Passwort-Zurücksetzungsabläufe Testen",
    "emailGeneratorPage.uc2P1": "Teste deine Passwort-Zurücksetzungsfunktionalität umfassend, indem du Testkonten mit temporären E-Mails erstellst, den Passwort-vergessen-Ablauf auslöst, Zurücksetzungs-E-Mails sofort erhältst und die Token-Sicherheit sowie Ablauflogik überprüfst.",
    "emailGeneratorPage.uc2P2": "Gültige Zurücksetzungsanfragen, abgelaufene Token, mehrere Zurücksetzungsversuche, ungültige E-Mail-Adressen, Ratenbegrenzung und kontoübergreifende Sicherheit.",
    "emailGeneratorPage.uc3Title": "3. Multi-User- und Rollenbasierte Tests",
    "emailGeneratorPage.uc3P1": "Das Testen von Anwendungen mit verschiedenen Benutzerrollen (Admin, Moderator, Benutzer) oder Multi-Tenant-Systemen erfordert mehrere einzigartige E-Mail-Adressen. Generiere verschiedene temporäre E-Mails für jeden Testbenutzer ohne den Aufwand, echte Konten zu verwalten.",
    "emailGeneratorPage.uc4Title": "4. E-Mail-Benachrichtigungssystem Testen",
    "emailGeneratorPage.uc4P1": "Wenn deine Anwendung transaktionale E-Mails sendet (Bestellbestätigungen, Warnungen, Erinnerungen, Statusaktualisierungen), verwende temporäre E-Mails, um zu überprüfen, dass E-Mails durch die richtigen Ereignisse ausgelöst werden, die Personalisierung korrekt gerendert wird, das HTML/CSS-Format richtig angezeigt wird und Links wie erwartet funktionieren.",
    "emailGeneratorPage.uc5Title": "5. Automatisierte Tests und CI/CD-Integration",
    "emailGeneratorPage.uc5P1": "Deine CI/CD-Pipeline führt automatisierte E2E-Tests durch, die E-Mail-basierte Workflows beinhalten. Jeder Testlauf braucht frische, einzigartige E-Mail-Adressen.",
    "emailGeneratorPage.uc5P2": "Generiere temporäre E-Mails programmatisch oder verwende konsistente Namensmuster, um einzigartige Adressen für jeden Testlauf ohne manuellen Eingriff zu erstellen. Perfekt für Playwright-, Cypress- oder Selenium-Testsuiten.",
    "emailGeneratorPage.uc6Title": "6. Integrationstests mit E-Mail-Drittanbieterdiensten",
    "emailGeneratorPage.uc6P1": "Das Testen von Integrationen mit SendGrid, Mailgun, AWS SES, Postmark oder anderen E-Mail-Diensten erfordert echte Empfängeradressen, um erfolgreiche E-Mail-Zustellung, Webhook-Ereignisse, Bounce-Handling-Logik, Template-Rendering und SPF/DKIM-Authentifizierung zu überprüfen.",
    "emailGeneratorPage.featuresTitle": "Funktionen für Entwickler",
    "emailGeneratorPage.f1": "Keine Einrichtung: Keine API-Schlüssel, keine Authentifizierung, keine Kontoerstellung. Seite besuchen, E-Mail-Adresse erhalten, mit dem Testen beginnen.",
    "emailGeneratorPage.f2": "Echtzeit-E-Mail-Empfang: E-Mails erscheinen in Sekunden im Posteingang. Kein Polling-Verzögerung, keine Stapelverarbeitung.",
    "emailGeneratorPage.f3": "Vollständiger E-Mail-Zugang: Sieh den gesamten E-Mail-Inhalt einschließlich HTML-Body, Nur-Text-Alternative, E-Mail-Header, Absenderinformationen und Anhänge.",
    "emailGeneratorPage.f4": "Benutzerdefinierte Aliase zur Organisation: Verwende beschreibende E-Mail-Adressen, die bestimmten Testfällen zugeordnet sind.",
    "emailGeneratorPage.f5": "Automatische Bereinigung: E-Mails werden nach 24 Stunden automatisch gelöscht. Keine manuelle Bereinigung, keine Verwaltung von Anmeldedaten, kein Wartungsaufwand.",
    "emailGeneratorPage.securityTitle": "Sicherheitshinweis für Entwickler",
    "emailGeneratorPage.securityWarn": "Temporäre E-Mails sind öffentlich und unsicher. Verwende sie NUR für Entwicklungsumgebungen, Staging-/QA-Umgebungen mit Testdaten, isolierte Testdatenbanken und Integrationstests mit Mock-/Test-APIs.",
    "emailGeneratorPage.securityNever": "Verwende temporäre E-Mails NIEMALS für: Produktionssysteme, echte Benutzerdaten, Zahlungstests (auch in der Sandbox), sensible Informationen oder Produktions-Datenbank-Anmeldedaten.",
    "emailGeneratorPage.startTitle": "Jetzt mit dem Testen Beginnen",
    "emailGeneratorPage.startP1": "Hör auf, Zeit mit der Verwaltung von Test-E-Mail-Konten zu verschwenden. Generiere sofort unbegrenzt temporäre E-Mails und konzentriere dich auf das Wesentliche — großartige Software bauen und testen. Keine Registrierung, keine Kosten, kein Aufwand.",
    "emailGeneratorPage.startP2": "Frontend-Entwickler, Backend-Ingenieure, QA-Tester, DevOps-Ingenieure, Automatisierungsspezialisten und jeder, der E-Mail-abhängige Funktionen entwickelt.",
    "tempGmailPage.h1": "Temp Gmail - Temporäre Gmail-Adressen Erstellen",
    "tempGmailPage.lead": "Generiere sofort Wegwerf-Gmail-Adressen, die aussehen und funktionieren wie echte Gmail-Konten. Schütze deinen persönlichen Posteingang vor Spam und unerwünschten Nachrichten.",
    "tempGmailPage.seoTitle1": "Verborgene Gmail-Datenschutzfunktionen: Plus-Adressierung und der Punkt-Trick",
    "tempGmailPage.seoP1": "Wusstest du, dass dein Gmail-Konto unbegrenzte E-Mail-Adressen generieren kann, ohne neue Konten zu erstellen? Gmail hat zwei leistungsstarke integrierte Funktionen, die die meisten Nutzer nicht kennen: Plus-Adressierung (Aliase) und den Punkt-Trick (Punktplatzierung). Fire Temp Mail hilft dir, diese Gmail-spezifischen Funktionen zu nutzen, um deine Privatsphäre zu schützen und deinen Posteingang zu organisieren.",
    "tempGmailPage.seoP2": "Dies sind keine \"Wegwerf\"-E-Mails eines Drittanbieterdienstes — es sind legitime Variationen deiner echten Gmail-Adresse, die direkt an deinen bestehenden Posteingang zugestellt werden, während du Nachrichten nach Quelle verfolgen, filtern und organisieren kannst.",
    "tempGmailPage.plusTitle": "Gmail Plus-Adressierung verstehen (Der \"+\"-Trick)",
    "tempGmailPage.plusP1": "Gmail ignoriert alles nach dem Pluszeichen (+) in deiner E-Mail-Adresse. Wenn deine E-Mail john.smith@gmail.com ist, werden alle diese an denselben Posteingang zugestellt:",
    "tempGmailPage.plusL1": "john.smith+shopping@gmail.com — Für Online-Shopping-Seiten",
    "tempGmailPage.plusL2": "john.smith+newsletters@gmail.com — Für Newsletter-Abonnements",
    "tempGmailPage.plusL3": "john.smith+facebook@gmail.com — Für Facebook-Anmeldung",
    "tempGmailPage.plusL4": "john.smith+netflix@gmail.com — Für Netflix-Test",
    "tempGmailPage.plusL5": "john.smith+spam@gmail.com — Für nicht vertrauenswürdige Seiten",
    "tempGmailPage.whyPlusTitle": "Warum Plus-Adressierung So Mächtig Ist",
    "tempGmailPage.whyPlusP1": "1. E-Mail-Verkäufer Aufspüren: Wenn du dich bei einem Dienst mit deinname+dienstX@gmail.com anmeldest und Spam an diese Adresse erhältst, weißt du genau, wer deine E-Mail an Vermarkter verkauft hat.",
    "tempGmailPage.whyPlusP2": "2. Automatisches Filtern: Erstelle Gmail-Filter basierend auf dem \"+\"-Label, um E-Mails automatisch in Ordner zu sortieren, Labels anzuwenden oder sogar Spam aus bestimmten Quellen automatisch zu löschen.",
    "tempGmailPage.whyPlusP3": "3. Anmeldungen Organisieren: Verwende verschiedene Labels für verschiedene Kategorien: +arbeit, +persönlich, +tests, +shopping. Sieh sofort, zu welcher Kategorie jede E-Mail gehört.",
    "tempGmailPage.whyPlusP4": "4. \"Ein E-Mail Pro Konto\"-Beschränkungen Umgehen: Einige Dienste (Foren, Gewinnspiele, Testversionen) erlauben nur ein Konto pro E-Mail. Verwende Plus-Adressierung, um \"mehrere\" Adressen zu erstellen.",
    "tempGmailPage.dotTitle": "Der Gmail-Punkt-Trick: Punktplatzierung Spielt Keine Rolle",
    "tempGmailPage.dotP1": "Gmail ignoriert Punkte im Benutzernamenteil deiner E-Mail-Adresse vollständig. Das bedeutet, dass johnsmith@gmail.com, john.smith@gmail.com, j.o.h.n.s.m.i.t.h@gmail.com alle an denselben Posteingang zugestellt werden.",
    "tempGmailPage.dotUseTitle": "Wie Man den Punkt-Trick Verwendet",
    "tempGmailPage.dotUseP1": "Mehrfach-Konto-Anmeldungen: Wenn eine Website nur eine E-Mail pro Person erlaubt, kannst du mehrere Konten mit verschiedenen Punktplatzierungen registrieren. Die Website sieht sie als verschiedene E-Mails, aber Gmail sieht sie alle als deine.",
    "tempGmailPage.combineTitle": "Plus-Adressierung UND Punkt-Trick Kombinieren",
    "tempGmailPage.combineP1": "Für maximale Flexibilität kombiniere beide Funktionen: j.o.h.n.smith+netflix@gmail.com. Dies erzeugt praktisch unbegrenzte einzigartige Adressen, die alle an deinen einzigen Gmail-Posteingang gehen, während sie maximale Verfolgungs- und Filtermöglichkeiten bieten.",
    "tempGmailPage.breachTitle": "Praxisbeispiel: Datenlecks Aufspüren",
    "tempGmailPage.breachP1": "Angenommen, du meldest dich bei \"ShoppingAppX\" mit deinname+shoppingappx@gmail.com an. Sechs Monate später erhältst du Spam an genau diese Adresse. Jetzt weißt du, dass ShoppingAppX:",
    "tempGmailPage.breachL1": "Deine E-Mail an Vermarkter verkauft hat",
    "tempGmailPage.breachL2": "Ein Datenleck hatte",
    "tempGmailPage.breachL3": "E-Mails mit \"Partnern\" teilt",
    "tempGmailPage.breachP2": "Jetzt kannst du einen Gmail-Filter erstellen, um automatisch alles zu löschen, was an deinname+shoppingappx@gmail.com gesendet wird, und so diese Spam-Quelle effektiv blockieren, ohne deine anderen E-Mails zu beeinträchtigen.",
    "tempGmailPage.filterTitle": "Gmail-Filter für Plus-Adressierung Einrichten",
    "tempGmailPage.filterP1": "Sobald du Plus-Adressierung verwendest, organisiere eingehende E-Mails automatisch:",
    "tempGmailPage.filterL1": "Gmail-Einstellungen Öffnen: Klicke auf das Zahnrad-Symbol → \"Alle Einstellungen anzeigen\"",
    "tempGmailPage.filterL2": "Zu \"Filter und blockierte Adressen\" gehen: Klicke auf \"Neuen Filter erstellen\"",
    "tempGmailPage.filterL3": "Filterregel Hinzufügen: Im \"An\"-Feld, gib deinname+shopping@gmail.com ein",
    "tempGmailPage.filterL4": "Aktion Wählen: Label \"Shopping\" anwenden, Posteingang überspringen, als gelesen markieren, weiterleiten oder löschen",
    "tempGmailPage.filterL5": "Filter Speichern: Klicke auf \"Filter erstellen\" und fertig",
    "tempGmailPage.filterP2": "Jetzt wird jede E-Mail, die an diese Adresse gesendet wird, automatisch nach deinen Regeln organisiert.",
    "tempGmailPage.limitTitle": "Einschränkungen der Integrierten Gmail-Funktionen",
    "tempGmailPage.limitP1": "Obwohl sie leistungsstark sind, haben Gmail's Plus-Adressierung und Punkt-Trick einige Einschränkungen:",
    "tempGmailPage.limitL1": "Nicht Wirklich Anonym: Deine Gmail-Basisadresse ist weiterhin sichtbar. Jeder kann das \"+label\" entfernen, um deine echte Adresse zu finden.",
    "tempGmailPage.limitL2": "Einige Seiten Blockieren das Plus-Zeichen: Manche Websites lehnen E-Mail-Adressen ab, die \"+\"-Symbole enthalten.",
    "tempGmailPage.limitL3": "Kein Google-Schutz: Google sieht weiterhin all deine Aktivitäten. Diese Tricks schützen dich nicht vor Googles Datensammlung.",
    "tempGmailPage.limitL4": "Einzelne Aliase Nicht Löschbar: Anders als echte Wegwerf-E-Mails kannst du einen Alias nicht \"verbrennen\", wenn er kompromittiert wird.",
    "tempGmailPage.limitL5": "Nicht für Risiko-Anmeldungen: Da deine echte Gmail technisch immer noch offengelegt ist, verwende diese Tricks nicht für nicht vertrauenswürdige Websites. Verwende stattdessen Fire Temp Mail.",
    "tempGmailPage.vsTitle": "Wann Gmail-Tricks vs. Echte Wegwerf-E-Mails Verwenden",
    "tempGmailPage.useGmailTitle": "Verwende Gmails Plus-Adressierung/Punkt-Trick Wenn:",
    "tempGmailPage.useGmailL1": "Du E-Mails in deinem Hauptposteingang erhalten möchtest",
    "tempGmailPage.useGmailL2": "Du verfolgen musst, welche Dienste deine E-Mail teilen/verkaufen",
    "tempGmailPage.useGmailL3": "Du E-Mails aus verschiedenen Quellen organisieren möchtest",
    "tempGmailPage.useGmailL4": "Der Dienst relativ vertrauenswürdig ist, aber Spam generiert",
    "tempGmailPage.useGmailL5": "Du möglicherweise langfristigen Zugang zum Konto brauchst",
    "tempGmailPage.useDispTitle": "Verwende Fire Temp Mails Vollständig Wegwerf-E-Mails Wenn:",
    "tempGmailPage.useDispL1": "Du vollständige Anonymität brauchst (keine Verbindung zu deiner echten E-Mail)",
    "tempGmailPage.useDispL2": "Du dich bei nicht vertrauenswürdigen oder riskanten Websites anmeldest",
    "tempGmailPage.useDispL3": "Einmalige Verifizierungen, die du nie wieder brauchst",
    "tempGmailPage.useDispL4": "Testen während der Entwicklung, ohne deinen echten Posteingang zu füllen",
    "tempGmailPage.useDispL5": "Dienste, die aggressiv Spam generieren oder Daten verkaufen könnten",
    "tempGmailPage.tipsTitle": "Gmail-Spezifische Datenschutztipps und Erweiterte Techniken",
    "tempGmailPage.tip1Title": "1. Ein \"Brenner\"-Filtersystem in Gmail Erstellen",
    "tempGmailPage.tip1P1": "Richte einen dedizierten Filter für alle Plus-adressierten E-Mails ein:",
    "tempGmailPage.tip1L1": "Filterbedingung: to:deinname+*@gmail.com",
    "tempGmailPage.tip1L2": "Aktion: Label \"Verfolgte Anmeldungen\" anwenden und Posteingang überspringen",
    "tempGmailPage.tip1L3": "Ergebnis: Alle Plus-adressierten E-Mails umgehen deinen Hauptposteingang und halten ihn sauber",
    "tempGmailPage.tip2Title": "2. Systematische Namenskonventionen Verwenden",
    "tempGmailPage.tip2P1": "Entwickle ein konsistentes Labeling-System:",
    "tempGmailPage.tip2L1": "+shop-[seitenname] — Shopping-Seiten",
    "tempGmailPage.tip2L2": "+news-[thema] — Newsletter",
    "tempGmailPage.tip2L3": "+test-[dienst] — Kostenlose Testversionen",
    "tempGmailPage.tip2L4": "+social-[plattform] — Soziale Netzwerke",
    "tempGmailPage.tip3Title": "3. Datenleck-Quellen Aufspüren",
    "tempGmailPage.tip3P1": "Wenn du Spam oder Phishing-E-Mails erhältst, überprüfe das \"An\"-Feld. Wenn dort deinname+bestimmteseite@gmail.com steht, hast du die Quelle des Lecks oder der Datenpanne identifiziert.",
    "tempGmailPage.ctaTitle": "Beginne Heute mit Gmails Datenschutzfunktionen",
    "tempGmailPage.ctaP1": "Gmails Plus-Adressierung und Punkt-Trick sind vollständig kostenlose, integrierte Funktionen, die sofort mit deinem bestehenden Gmail-Konto funktionieren. Keine Anmeldung, kein Drittanbieterdienst, kein Risiko. Beginne damit, deine Privatsphäre zu schützen und deinen Posteingang zu organisieren, indem du diese leistungsstarken Gmail-spezifischen Funktionen nutzt.",
    "tempGmailPage.ctaP2": "Für Situationen, die vollständige Anonymität erfordern: Verwende Fire Temp Mails echte Wegwerf-E-Mail-Adressen auf der Hauptseite. Für alles andere nutze die hier erklärten integrierten Gmail-Datenschutzfunktionen.",
    "burnerEmailPage.h1": "Kostenloser Brenner-E-Mail-Generator – Sofort Wegwerf-Adressen Erstellen",
    "burnerEmailPage.lead": "Generiere sofort anonyme Brenner-E-Mail-Adressen. Perfekt zum Schutz deiner echten Online-Identität — keine Anmeldung, keine persönlichen Daten erforderlich.",
    "burnerEmailPage.seoTitle": "Was Ist eine Brenner-E-Mail und Warum Brauchst Du Eine?",
    "burnerEmailPage.seoP1": "Eine Brenner-E-Mail ist eine wegwerfbare, temporäre E-Mail-Adresse, mit der du Nachrichten senden oder empfangen kannst, ohne deine wahre Identität preiszugeben. Anders als ein reguläres E-Mail-Konto, das du jahrelang behältst, ist eine Brenner-E-Mail absichtlich kurzlebig und anonym — dafür konzipiert, einmal verwendet und dann verworfen zu werden.",
    "burnerEmailPage.seoP2": "Der Begriff \"Brenner\" stammt von \"Brenner-Handys\" — vorausbezahlte, nicht nachverfolgbare Telefone für temporäre Kommunikation. Brenner-E-Mails funktionieren genauso: Sie schaffen eine Trennschicht zwischen deiner echten Identität und der Online-Welt.",
    "burnerEmailPage.howTitle": "Wie Brenner-E-Mails Funktionieren",
    "burnerEmailPage.howP1": "Brenner-E-Mail-Dienste wie Fire Temp Mail generieren eine zufällige E-Mail-Adresse in dem Moment, in dem du die Website besuchst. Du musst kein Konto erstellen, keine persönlichen Informationen eingeben und nichts verifizieren. So funktioniert es:",
    "burnerEmailPage.howL1": "Sofortige Generierung: Besuche die Website und erhalte sofort eine zufällige, anonyme E-Mail-Adresse.",
    "burnerEmailPage.howL2": "E-Mails Empfangen: Verwende die Adresse, um dich bei Diensten anzumelden, Verifizierungscodes zu erhalten oder einmalige Nachrichten zu empfangen.",
    "burnerEmailPage.howL3": "Keine Identitätsverknüpfung: Die Adresse hat keine Verbindung zu deinem echten Namen, Telefonnummer oder permanenter E-Mail.",
    "burnerEmailPage.howL4": "Automatischer Ablauf: Nach einem kurzen Zeitraum (normalerweise 24 Stunden) werden die E-Mail-Adresse und alle zugehörigen Nachrichten dauerhaft gelöscht.",
    "burnerEmailPage.howL5": "Unbegrenzte Adressen: Generiere so viele Brenner-Adressen wie nötig. Jede ist vollständig unabhängig.",
    "burnerEmailPage.usesTitle": "Wichtigste Anwendungsfälle für Brenner-E-Mails",
    "burnerEmailPage.use1Title": "1. Website-Registrierungen und Anmeldungen",
    "burnerEmailPage.use1P": "Die meisten Websites verlangen eine E-Mail-Adresse zur Kontoerstellung. Brenner-E-Mails ermöglichen dir die Anmeldung, ohne deinen echten Posteingang mit Werbe-E-Mails und Newslettern zu überschwemmen.",
    "burnerEmailPage.use2Title": "2. Kostenlose Testversionen",
    "burnerEmailPage.use2P": "Viele Dienste bieten zeitlich begrenzte kostenlose Testversionen an, erfordern aber eine E-Mail-Adresse. Verwende eine Brenner-E-Mail, um den Dienst risikofrei zu testen.",
    "burnerEmailPage.use3Title": "3. Online-Shopping und Gutscheine",
    "burnerEmailPage.use3P": "Einzelhandels-Websites verlangen häufig eine E-Mail für den Checkout oder zum Freischalten von Rabatten. Eine Brenner-E-Mail verhindert Post-Kauf-Spam und gibt dir trotzdem Zugang zu Angeboten.",
    "burnerEmailPage.use4Title": "4. Öffentliches WLAN-Login",
    "burnerEmailPage.use4P": "Cafés, Flughäfen und Hotels verlangen häufig eine E-Mail-Adresse für den Zugang zu ihren WLAN-Netzwerken. Verwende eine Brenner-E-Mail statt deiner persönlichen.",
    "burnerEmailPage.use5Title": "5. Ressourcen Herunterladen",
    "burnerEmailPage.use5P": "E-Books, Whitepapers, Vorlagen und andere herunterladbare Ressourcen stehen meist hinter einer E-Mail-Schranke. Brenner-E-Mails ermöglichen dir den Zugriff auf den Inhalt, ohne dich bei unerwünschten Mailinglisten anzumelden.",
    "burnerEmailPage.use6Title": "6. Forum- und Community-Registrierungen",
    "burnerEmailPage.use6P": "Foren, Reddit-ähnliche Communities und Diskussionsforen erfordern häufig E-Mails zur Kontoerstellung. Verwende eine Brenner-E-Mail für anonyme Teilnahme.",
    "burnerEmailPage.use7Title": "7. Entwickler- und QA-Tests",
    "burnerEmailPage.use7P": "Softwareentwickler und Tester brauchen ständig frische E-Mail-Adressen zum Testen von Registrierungsabläufen, Verifizierungssystemen und Benachrichtigungsfunktionen.",
    "burnerEmailPage.benefitsTitle": "Vorteile der Verwendung von Brenner-E-Mails",
    "burnerEmailPage.ben1": "Datenschutz: Deine echte E-Mail bleibt verborgen. Niemand kann eine Brenner-E-Mail zu dir zurückverfolgen.",
    "burnerEmailPage.ben2": "Spam-Prävention: Aller Spam geht an die Brenner-Adresse und hält deinen echten Posteingang für immer sauber.",
    "burnerEmailPage.ben3": "Datenleck-Sicherheit: Wenn der Dienst, bei dem du dich angemeldet hast, gehackt wird, ist deine echte E-Mail nicht in der geleakten Benutzerliste.",
    "burnerEmailPage.ben4": "Keine Kontoverwaltung: Keine Passwörter zum Merken. Keine zusätzlichen Konten zum Pflegen.",
    "burnerEmailPage.ben5": "Sofort und Kostenlos: Keine Registrierung nötig. Keine Kosten. Einfach besuchen, generieren und verwenden.",
    "burnerEmailPage.vsTitle": "Brenner-E-Mail vs. Reguläre E-Mail vs. E-Mail-Alias",
    "burnerEmailPage.vsP1": "Reguläre E-Mail (Gmail, Outlook): Permanent, mit deiner Identität verknüpft, für langfristige Kommunikation verwendet. Anfällig für Spam und Datenlecks.",
    "burnerEmailPage.vsP2": "E-Mail-Aliase (+Tags, Punkte): Variationen deiner echten E-Mail, die trotzdem an deinen Posteingang zugestellt werden. Nützlich zur Organisation, verbergen aber nicht deine echte Adresse.",
    "burnerEmailPage.vsP3": "Brenner-E-Mail (Fire Temp Mail): Vollständig von deiner echten Identität getrennt. Temporär, anonym, selbstlöschend. Am besten für Privatsphäre und einmalige Nutzung.",
    "eduEmailPage.h1": "Kostenloser EDU-E-Mail-Generator – Sofort ein Wegwerf-.EDU-Postfach Erstellen",
    "eduEmailPage.lead": "Generiere .EDU-E-Mails mit unserem kostenlosen EDU-E-Mail-Generator. Perfekt für Anmeldungen, Tests, Studentenrabatte und mehr — ohne deinen echten Posteingang Spam auszusetzen.",
    "eduEmailPage.seoTitle": "Top Studentenrabatte und .EDU-E-Mail-Vorteile",
    "eduEmailPage.seoP1": "Studentenrabatte können dir Tausende von Dollar pro Jahr bei Software, Streaming-Diensten und Lernressourcen sparen.",
    "eduEmailPage.discountsTitle": "Top Studentenrabatte mit .EDU-Verifizierung",
    "eduEmailPage.spotifyTitle": "Spotify Premium Student - 5,99$/Monat (50% Rabatt)",
    "eduEmailPage.spotifyP1": "Normalpreis: 10,99$/Monat | Studentenersparnis: 60$/Jahr",
    "eduEmailPage.spotifyP2": "Beinhaltet Hulu (mit Werbung) und SHOWTIME ohne Zusatzkosten. Verifiziert über SheerID mit deiner .EDU-E-Mail.",
    "eduEmailPage.amazonTitle": "Amazon Prime Student - 7,49$/Monat",
    "eduEmailPage.amazonP1": "Normalpreis: 14,99$/Monat | Studentenersparnis: 90$/Jahr + 6 Monate GRATIS-Testversion",
    "eduEmailPage.amazonP2": "Alle Prime-Vorteile: Kostenloser 2-Tage-Versand, Prime Video, Prime Music, unbegrenzter Fotospeicher und mehr.",
    "eduEmailPage.adobeTitle": "Adobe Creative Cloud - 60% Rabatt",
    "eduEmailPage.adobeP1": "Normalpreis: 59,99$/Monat | Studentenpreis: 19,99$/Monat | Ersparnis: 480$/Jahr",
    "eduEmailPage.adobeP2": "Komplette Suite: Photoshop, Illustrator, Premiere Pro, After Effects, InDesign und über 20 Apps.",
    "eduEmailPage.appleTitle": "Apple Music Student - 5,99$/Monat",
    "eduEmailPage.appleP1": "Normalpreis: 10,99$/Monat | Studentenersparnis: 60$/Jahr",
    "eduEmailPage.appleP2": "Vollständiger Apple Music Katalog plus kostenloses Apple TV+ Abonnement inklusive.",
    "eduEmailPage.githubTitle": "GitHub Student Developer Pack - KOSTENLOS",
    "eduEmailPage.githubP1": "Normaler Wert: $200+/Jahr an Tools | Studentenpreis: Komplett KOSTENLOS",
    "eduEmailPage.githubP2": "GitHub Pro, kostenlose Domain, Cloud-Guthaben, CI/CD-Tools und über 20 Entwicklertools und -dienste.",
    "bestTempMailPage.h1": "Beste Temp Mail – Nr. 1 Kostenloser Temporärer Wegwerf-E-Mail-Dienst",
    "bestTempMailPage.lead": "Der beste temporäre E-Mail-Dienst online. Generiere sofort Wegwerf-E-Mail-Adressen — keine Anmeldung, keine persönlichen Informationen nötig. Privat, schnell und kostenlos.",
    "bestTempMailPage.seoTitle": "Warum Fire Temp Mail der Beste Temporäre E-Mail-Dienst Ist",
    "bestTempMailPage.seoP1": "Bei dutzenden temporären E-Mail-Diensten online ist die richtige Wahl wichtig. Fire Temp Mail hebt sich aus mehreren wichtigen Gründen als bester Temp-Mail-Dienst ab.",
    "bestTempMailPage.comparison": "Funktionsvergleich mit Anderen Diensten",
    "bestTempMailPage.whyBestTitle": "Was Uns zum Besten Macht",
    "bestTempMailPage.whyBestP1": "Fire Temp Mail vereint Geschwindigkeit, Datenschutz und Einfachheit auf eine Weise, die kein anderer temporärer E-Mail-Dienst bietet.",
    "bestTempMailPage.feature1": "Sofortige Generierung: Kein Warten, keine Anmeldung. Seite besuchen und deine temporäre E-Mail ist sofort bereit.",
    "bestTempMailPage.feature2": "Mehrere Domains: Wähle aus verschiedenen E-Mail-Domains, die am besten zu deinen Bedürfnissen passen.",
    "bestTempMailPage.feature3": "Gmail-Stil-Adressen: Erhalte temporäre Gmail-ähnliche Adressen, die überall funktionieren.",
    "bestTempMailPage.feature4": "Benutzerdefinierte Aliase: Erstelle personalisierte temporäre Adressen zur Organisation.",
    "bestTempMailPage.feature5": "Auto-Aktualisierung: Neue E-Mails erscheinen automatisch ohne manuelles Aktualisieren.",
    "bestTempMailPage.feature6": "Datenschutz Zuerst: Kein Tracking, keine Protokollierung, keine Datensammlung.",
    "gmailGeneratorPage.h1": "Kostenloser Gmail-Generator – Sofort Temporäre Gmail-Adressen Erstellen",
    "gmailGeneratorPage.lead": "Generiere kostenlos eine temporäre Gmail-Adresse mit unserem Gmail-Generator. Zugang zu einem Wegwerf-Gmail-Postfach sofort — keine Anmeldung, keine persönlichen Daten. Bleib anonym online.",
    "gmailGeneratorPage.seoTitle": "Wie der Gmail-Generator Funktioniert",
    "gmailGeneratorPage.seoP1": "Unser Gmail-Generator erstellt Wegwerf-Gmail-ähnliche Adressen, die wie echte Gmail-Konten funktionieren. Verwende sie für Anmeldungen, Verifizierungen und Tests, ohne deine echte Gmail-Adresse preiszugeben.",
    "gmailGeneratorPage.howItWorksTitle": "So Funktioniert Es",
    "gmailGeneratorPage.howItWorksP1": "1. Besuche Fire Temp Mail und wähle die Gmail-Option. 2. Eine temporäre Gmail-ähnliche Adresse wird sofort generiert. 3. Verwende sie für jede Online-Anmeldung oder Verifizierung. 4. Empfange E-Mails in Echtzeit in deinem privaten Postfach. 5. Die Adresse läuft automatisch nach 24 Stunden ab.",
    "temporaryGmailPage.h1": "Temporäres Gmail – Kostenlose Wegwerf-Gmail-Adressen",
    "temporaryGmailPage.lead": "Erhalte eine kostenlose temporäre Gmail-Adresse, die genau wie ein echtes Gmail-Konto funktioniert. Perfekt für Anmeldungen, Verifizierungen und den Schutz deines Hauptposteingangs vor Spam.",
    "temporaryGmailPage.seoTitle": "Temporäre Gmail-Adressen Erklärt",
    "temporaryGmailPage.seoP1": "Eine temporäre Gmail-Adresse ist eine kurzlebige Wegwerf-E-Mail, die aussieht und funktioniert wie ein echtes Gmail-Konto. Sie ermöglicht es dir, Verifizierungs-E-Mails zu empfangen, dich bei Diensten anzumelden und die Privatsphäre zu wahren, ohne deine permanente E-Mail preiszugeben.",
    "temporaryGmailPage.benefitsTitle": "Vorteile des Temporären Gmails",
    "temporaryGmailPage.benefitsP1": "Schütze dein echtes Gmail vor Spam, vermeide Datenlecks und melde dich anonym bei Diensten an. Alles ohne Registrierung erforderlich.",
    "tempMailEduPage.h1": "Temp Mail EDU – Kostenloser Temporärer .EDU-E-Mail-Generator",
    "tempMailEduPage.lead": "Generiere sofort temporäre .EDU-E-Mail-Adressen. Zugang zu Studentenrabatten, Bildungsressourcen und Online-Tools mit einem Wegwerf-.EDU-Postfach.",
    "tempMailEduPage.seoTitle": "Temp Mail für Bildungszwecke Verwenden",
    "tempMailEduPage.seoP1": "Temporäre .EDU-E-Mails können dir helfen, auf Bildungsressourcen zuzugreifen, Studentenverifizierungssysteme zu testen und Plattformfunktionen zu erkunden, die für die akademische Gemeinschaft konzipiert sind.",
    "tenMinuteMailPage.h1": "10 Minuten Mail – Schnelle Wegwerf-E-Mail, die Schnell Abläuft",
    "tenMinuteMailPage.lead": "Brauchst du eine schnelle Wegwerf-E-Mail? Unsere 10 Minuten Mail gibt dir eine sofortige Wegwerfadresse, die sich selbst löscht. Perfekt für einmalige Anmeldungen und Verifizierungen.",
    "tenMinuteMailPage.seoTitle": "Was ist 10 Minuten Mail und Wie Funktioniert Es?",
    "tenMinuteMailPage.seoP1": "10 Minuten Mail ist ein Wegwerf-E-Mail-Dienst, der dir eine temporäre E-Mail-Adresse gibt, die nur 10 Minuten gültig ist. Es ist der schnellste Weg, eine Wegwerf-E-Mail für schnelle Anmeldungen und Verifizierungen zu bekommen.",
    "tenMinuteMailPage.howTitle": "Wie 10 Minuten Mail Funktioniert",
    "tenMinuteMailPage.howP1": "Besuche die Seite und erhalte sofort eine E-Mail-Adresse. Verwende sie für jede Anmeldung oder Verifizierung. Die Adresse und alle E-Mails werden nach 10 Minuten dauerhaft gelöscht.",
    "tenMinuteMailPage.whyTitle": "Warum 10 Minuten Mail Verwenden?",
    "tenMinuteMailPage.whyP1": "Manchmal brauchst du keine E-Mail-Adresse für lange Zeit. Schnelle Anmeldungen, einmalige Verifizierungen und das Herunterladen geschützter Inhalte sind perfekte Anwendungsfälle für 10 Minuten Mail.",
    "tenMinuteMailPage.vsTitle": "10 Minuten Mail vs. Reguläre Temp Mail",
    "tenMinuteMailPage.vsP1": "10 Minuten Mail ist schneller und für ultra-schnelle Anwendungsfälle konzipiert. Reguläre temporäre E-Mail (wie Fire Temp Mail) hält länger (bis zu 24 Stunden) und ist besser für Tests, Entwicklung und Situationen, wo du die E-Mail für mehr als ein paar Minuten brauchst.",
    "temporaryEmailGenPage.h1": "Temporärer E-Mail-Generator – Kostenlos Wegwerf-E-Mail-Adressen Erstellen",
    "temporaryEmailGenPage.lead": "Generiere sofort temporäre E-Mail-Adressen. Unser Temporärer E-Mail-Generator bietet kostenlose Wegwerf-Postfächer — perfekt zum Schutz deiner Online-Privatsphäre.",
    "temporaryEmailGenPage.seoTitle": "Wie Temporäre E-Mail-Generatoren Funktionieren",
    "temporaryEmailGenPage.seoP1": "Ein temporärer E-Mail-Generator erstellt kurzlebige, anonyme E-Mail-Adressen auf Abruf. Diese Adressen funktionieren wie reguläre E-Mails, laufen aber automatisch ab und halten deine echte Identität geschützt.",
    "fireMailPage.h1": "Fire Mail – Schneller und Kostenloser Temporärer E-Mail-Dienst",
    "fireMailPage.lead": "Fire Mail bietet sofortige temporäre E-Mail-Adressen für vollständige Online-Privatsphäre. Keine Anmeldung, keine persönlichen Daten — nur reine, verschlüsselte Wegwerf-E-Mail.",
    "fireMailPage.seoTitle": "Warum Fire Mail für Temporäre E-Mail Wählen",
    "fireMailPage.seoP1": "Fire Mail ist auf Geschwindigkeit, Datenschutz und Zuverlässigkeit ausgelegt. Unser temporärer E-Mail-Dienst generiert Wegwerf-Adressen sofort, mit Echtzeit-Posteingang-Updates und automatischer Bereinigung.",
    "gmailnatorPage.h1": "Gmailnator-Alternative – Kostenloser Temporärer Gmail-Generator",
    "gmailnatorPage.lead": "Suchst du eine Alternative zu Gmailnator? Fire Temp Mail bietet die gleiche Funktionalität mit besserem Datenschutz, schnellerer Leistung und zuverlässigerer E-Mail-Zustellung.",
    "gmailnatorPage.seoTitle": "Beste Gmailnator-Alternative 2024",
    "gmailnatorPage.seoP1": "Gmailnator war ein beliebter Dienst zum Generieren temporärer Gmail-Adressen. Fire Temp Mail bietet die gleiche Funktionalität mit verbesserter Zuverlässigkeit, besserem Datenschutz und einer modernen Benutzererfahrung.",
    "about.metaTitle": "Über Fire Temp Mail - Unsere Mission und Geschichte",
    "about.metaDescription": "Erfahre mehr über Fire Temp Mail — einen kostenlosen temporären E-Mail-Dienst, der deine Online-Privatsphäre schützt. Unsere Mission und Werte.",
    "about.title": "Über Fire Temp Mail",
    "about.subtitle": "Schutz deiner digitalen Privatsphäre, eine temporäre E-Mail nach der anderen",
    "about.missionTitle": "Unsere Mission",
    "about.missionP1": "Fire Temp Mail wurde geschaffen, um ein einfaches, aber kritisches Problem zu lösen: die Erosion der Online-Privatsphäre. Jeden Tag werden Millionen von Menschen gezwungen, ihre persönlichen E-Mail-Adressen anzugeben, um auf Dienste zuzugreifen, sich für Testversionen anzumelden oder Ressourcen herunterzuladen — was häufig zu einem von Spam und unerwünschten Marketing-E-Mails überfluteten Posteingang führt.",
    "about.missionP2": "Wir glauben, dass deine E-Mail-Adresse persönlich ist. Du solltest deine Privatsphäre nicht opfern oder die Sicherheit deines Posteingangs kompromittieren müssen, nur um auf Online-Dienste zuzugreifen. Deshalb haben wir Fire Temp Mail gebaut: einen vollständig kostenlosen, registrierungsfreien temporären E-Mail-Dienst, der deine Privatsphäre an erste Stelle setzt.",
    "about.whatWeDoTitle": "Was Wir Tun",
    "about.whatWeDoP1": "Fire Temp Mail bietet sofortige, anonyme und wegwerfbare E-Mail-Adressen, die jeder nutzen kann — ohne Registrierung. Ob du eine temporäre E-Mail für eine einmalige Anmeldung brauchst, Newsletter-Spam vermeiden oder deine echte Identität online schützen möchtest, wir haben die Lösung.",
    "about.whatWeDo1": "Sofortige E-Mail-Generierung — besuche einfach die Seite und erhalte eine funktionierende E-Mail-Adresse",
    "about.whatWeDo2": "Echtzeit-Posteingang — empfange E-Mails sofort in deinem Browser",
    "about.whatWeDo3": "Mehrere Domains — wähle aus verschiedenen verfügbaren E-Mail-Domains",
    "about.whatWeDo4": "Benutzerdefinierte Aliase — erstelle personalisierte temporäre Adressen",
    "about.whatWeDo5": "Gmail-Stil-Adressen — erhalte temporäre Gmail-ähnliche Adressen",
    "about.whatWeDo6": "Auto-Löschung — E-Mails werden automatisch für vollständige Privatsphäre bereinigt",
    "about.whyTitle": "Warum Fire Temp Mail?",
    "about.whyP1": "In einer Welt, in der Datenlecks, Spam und unerwünschtes Marketing alltägliche Probleme sind, bietet Fire Temp Mail eine einfache, aber leistungsstarke Lösung.",
    "about.why1": "Für immer kostenlos — keine versteckten Kosten, Abonnements oder Premium-Beschränkungen",
    "about.why2": "Keine Registrierung — sofort loslegen, kein Konto nötig",
    "about.why3": "Datenschutz zuerst — wir verfolgen, verkaufen oder monetarisieren deine Daten nicht",
    "about.why4": "Offen und transparent — unkomplizierter Dienst ohne Tricks",
    "about.why5": "Schnell und zuverlässig — auf moderner Infrastruktur für Geschwindigkeit aufgebaut",
    "about.valuesTitle": "Unsere Werte",
    "about.value1Title": "Datenschutz Über Alles",
    "about.value1Text": "Wir glauben, dass Privatsphäre ein Grundrecht ist. Unser Dienst ist von Grund auf so konzipiert, dass er deine schützt.",
    "about.value2Title": "Einfachheit",
    "about.value2Text": "Eine temporäre E-Mail zu bekommen sollte mühelos sein. Besuche unsere Seite, hol dir eine E-Mail, nutze sie. Das war's.",
    "about.value3Title": "Transparenz",
    "about.value3Text": "Keine versteckten Absichten. Wir sind offen darüber, wie unser Dienst funktioniert und wie wir ihn aufrechterhalten.",
    "about.value4Title": "Zugänglichkeit",
    "about.value4Text": "Jeder verdient Privatsphäre. Deshalb ist Fire Temp Mail für jeden kostenlos, überall.",
    "about.futureTitle": "Blick in die Zukunft",
    "about.futureP1": "Wir verbessern Fire Temp Mail ständig, um unseren Nutzern besser zu dienen. Unsere Roadmap umfasst verbesserte Sicherheitsfunktionen, mehr Domain-Optionen, ein verbessertes mobiles Erlebnis und zusätzliche Tools zum Schutz deiner digitalen Privatsphäre.",
    "about.futureP2": "Danke, dass du Fire Temp Mail mit deiner Online-Privatsphäre vertraust. Gemeinsam bauen wir ein sichereres und privateres Internet auf — eine temporäre E-Mail nach der anderen.",
    "about.contactTitle": "Kontakt Aufnehmen",
    "about.contactP1": "Hast du Fragen, Feedback oder möchtest einfach Hallo sagen? Wir freuen uns von dir zu hören.",
    "about.contactEmail": "Schreib uns eine E-Mail an",
    "about.contactLink": "Oder besuche unsere Kontaktseite"
}

for dotpath, value in t.items():
    set_nested(locale, dotpath, value)

with open(os.path.join(BASE, 'de.json'), 'w') as f:
    json.dump(locale, f, indent=2, ensure_ascii=False)
print(f"Updated de.json with {len(t)} new keys")
