#!/usr/bin/env python3
"""Generate French (FR) translations for all missing keys."""
import json, os

BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'src/lib/i18n/locales')

def set_nested(obj, dotpath, value):
    parts = dotpath.split('.')
    for part in parts[:-1]:
        if part not in obj: obj[part] = {}
        obj = obj[part]
    obj[parts[-1]] = value

with open(os.path.join(BASE, 'fr.json'), 'r') as f:
    locale = json.load(f)

t = {
    "email.generateNew": "Générer Nouveau",
    "email.changeDomain": "Changer de Domaine",
    "email.refreshPage": "Actualiser la Page",
    "email.generateCustomEmail": "Générer un Email Personnalisé",
    "email.waitingForEmails": "En attente d'emails entrants",
    "email.refreshStopped": "Actualisation automatique arrêtée",
    "email.inboxEmpty": "Votre boîte de réception est vide",
    "email.domain": "Domaine",
    "email.gmail": "Gmail",
    "email.googlemail": "GoogleMail",
    "email.copyToClipboard": "Copier dans le presse-papiers",
    "email.useCustomAlias2": "Utiliser un alias personnalisé",
    "email.changeDomain2": "Changer de domaine",
    "email.refreshPage2": "Actualiser la page",
    "email.scenario": "Scénario :",
    "email.solution": "Solution :",
    "email.challenge": "Défi :",
    "email.testingWorkflow": "Flux de test :",
    "email.testScenarios": "Scénarios de test :",
    "email.perfectFor": "Parfait pour :",
    "email.important": "IMPORTANT :",
    "email.neverUse": "N'utilisez JAMAIS les emails temporaires pour :",
    "emailGeneratorPage.h1": "Fire Temp Mail – Votre Générateur d'Email Jetable Gratuit",
    "emailGeneratorPage.lead": "Générez instantanément une adresse email jetable. Gardez votre vrai email privé et votre boîte de réception propre de messages indésirables et de spam.",
    "emailGeneratorPage.seoTitle": "Générateur d'Email pour Développeurs et Tests QA",
    "emailGeneratorPage.seoDesc": "Générateur d'email temporaire professionnel conçu spécifiquement pour les développeurs logiciels, ingénieurs QA et testeurs d'automatisation. Générez des adresses email jetables illimitées pour tester les flux d'inscription, les systèmes de vérification d'email, les réinitialisations de mot de passe et la logique de notification — sans gérer de comptes de test ni remplir de boîtes de réception personnelles.",
    "emailGeneratorPage.whyTitle": "Pourquoi les Développeurs ont Besoin d'Emails Jetables pour les Tests",
    "emailGeneratorPage.whyP1": "Tester les fonctionnalités dépendantes de l'email est essentiel mais pénible. Vous devez vérifier l'inscription des utilisateurs, les liens de confirmation par email, les flux de réinitialisation de mot de passe et les systèmes de notification — mais créer des dizaines de vrais comptes email est lent, non viable et remplit votre boîte de réception.",
    "emailGeneratorPage.whyP2": "Fire Temp Mail fournit des adresses email instantanées et jetables conçues spécifiquement pour les tests logiciels. Générez des emails temporaires illimités pour tester les flux email de votre application sans gérer de comptes de test ni vous battre avec les restrictions des fournisseurs d'email.",
    "emailGeneratorPage.painPointsTitle": "Problèmes Courants des Développeurs (Résolus)",
    "emailGeneratorPage.pp1": "Création manuelle de comptes test Gmail/Outlook → Générez des emails illimités instantanément",
    "emailGeneratorPage.pp2": "Gestion de mots de passe pour plusieurs comptes test → Aucune identification nécessaire",
    "emailGeneratorPage.pp3": "Nettoyage des anciennes données de test → Suppression automatique après 24 heures",
    "emailGeneratorPage.pp4": "Fournisseurs d'email bloquant les inscriptions automatisées → Vrais domaines qui fonctionnent partout",
    "emailGeneratorPage.pp5": "Test de scénarios multi-utilisateurs → Adresses uniques illimitées à la demande",
    "emailGeneratorPage.pp6": "Pipelines CI/CD nécessitant des emails frais → Génération sans configuration",
    "emailGeneratorPage.uc1Title": "1. Tests d'Inscription Utilisateur et Vérification d'Email",
    "emailGeneratorPage.uc1P1": "Votre application nécessite une vérification d'email lors de l'inscription. Vous devez tester que les emails de vérification arrivent, que les liens fonctionnent correctement, que les tokens expirent convenablement et que les cas limites sont gérés.",
    "emailGeneratorPage.uc1P2": "Générez un email temporaire → Inscrivez-vous dans votre app → Vérifiez la boîte de réception pour l'email de vérification (arrive en secondes) → Extrayez le lien/token de vérification → Complétez la vérification → Testez les cas limites (tokens expirés, vérifications dupliquées).",
    "emailGeneratorPage.uc2Title": "2. Tests du Flux de Réinitialisation de Mot de Passe",
    "emailGeneratorPage.uc2P1": "Testez exhaustivement votre fonctionnalité de réinitialisation de mot de passe en générant des comptes test avec des emails temporaires, en déclenchant le flux mot de passe oublié, en recevant les emails de réinitialisation instantanément et en vérifiant la sécurité des tokens et la logique d'expiration.",
    "emailGeneratorPage.uc2P2": "Demandes de réinitialisation valides, tokens expirés, tentatives de réinitialisation multiples, adresses email invalides, limitation de débit et sécurité inter-comptes.",
    "emailGeneratorPage.uc3Title": "3. Tests Multi-Utilisateurs et Basés sur les Rôles",
    "emailGeneratorPage.uc3P1": "Tester des applications avec différents rôles utilisateur (admin, modérateur, utilisateur) ou des systèmes multi-tenant nécessite plusieurs adresses email uniques. Générez des emails temporaires distincts pour chaque utilisateur test sans la charge de gérer de vrais comptes.",
    "emailGeneratorPage.uc4Title": "4. Tests du Système de Notification par Email",
    "emailGeneratorPage.uc4P1": "Si votre application envoie des emails transactionnels (confirmations de commande, alertes, rappels, mises à jour de statut), utilisez des emails temporaires pour vérifier que les emails sont déclenchés par les bons événements, que la personnalisation s'affiche correctement, que le format HTML/CSS est rendu correctement et que les liens fonctionnent comme prévu.",
    "emailGeneratorPage.uc5Title": "5. Tests Automatisés et Intégration CI/CD",
    "emailGeneratorPage.uc5P1": "Votre pipeline CI/CD exécute des tests E2E automatisés impliquant des workflows basés sur l'email. Chaque exécution de test nécessite des adresses email fraîches et uniques.",
    "emailGeneratorPage.uc5P2": "Générez des emails temporaires programmatiquement ou utilisez des modèles de nommage cohérents pour créer des adresses uniques pour chaque exécution de test sans intervention manuelle. Parfait pour les suites de tests Playwright, Cypress ou Selenium.",
    "emailGeneratorPage.uc6Title": "6. Tests d'Intégration avec des Services Email Tiers",
    "emailGeneratorPage.uc6P1": "Tester les intégrations avec SendGrid, Mailgun, AWS SES, Postmark ou d'autres fournisseurs de services email nécessite de vraies adresses de destinataires pour vérifier la livraison réussie des emails, les événements webhook, la logique de gestion des rebonds, le rendu des templates et l'authentification SPF/DKIM.",
    "emailGeneratorPage.featuresTitle": "Fonctionnalités pour Développeurs",
    "emailGeneratorPage.f1": "Aucune Configuration : Pas de clés API, pas d'authentification, pas de création de compte. Visitez la page, obtenez une adresse email, commencez à tester.",
    "emailGeneratorPage.f2": "Réception d'Email en Temps Réel : Les emails apparaissent dans la boîte de réception en secondes. Pas de délai de polling, pas de traitement par lots.",
    "emailGeneratorPage.f3": "Accès Complet à l'Email : Consultez le contenu complet de l'email incluant le corps HTML, l'alternative texte brut, les en-têtes d'email, les informations de l'expéditeur et les pièces jointes.",
    "emailGeneratorPage.f4": "Alias Personnalisés pour l'Organisation : Utilisez des adresses email descriptives correspondant à des cas de test spécifiques.",
    "emailGeneratorPage.f5": "Nettoyage Automatique : Les emails sont automatiquement supprimés après 24 heures. Pas de nettoyage manuel, pas de gestion d'identifiants, pas de charge de maintenance.",
    "emailGeneratorPage.securityTitle": "Rappel de Sécurité pour les Développeurs",
    "emailGeneratorPage.securityWarn": "Les emails temporaires sont publics et non sécurisés. Utilisez-les UNIQUEMENT pour les environnements de développement, le staging/QA avec des données de test, les bases de données de test isolées et les tests d'intégration avec des APIs mock/test.",
    "emailGeneratorPage.securityNever": "N'utilisez JAMAIS les emails temporaires pour : Les systèmes de production, les données réelles d'utilisateurs, les tests de paiement (même en sandbox), les informations sensibles ou les identifiants de bases de données de production.",
    "emailGeneratorPage.startTitle": "Commencez à Tester Maintenant",
    "emailGeneratorPage.startP1": "Arrêtez de perdre du temps à gérer des comptes email de test. Générez des emails temporaires illimités instantanément et concentrez-vous sur l'essentiel — construire et tester d'excellents logiciels. Sans inscription, sans coût, sans complication.",
    "emailGeneratorPage.startP2": "Développeurs frontend, ingénieurs backend, testeurs QA, ingénieurs DevOps, spécialistes en automatisation et toute personne développant des fonctionnalités dépendantes de l'email.",
    "tempGmailPage.h1": "Temp Gmail - Créer des Adresses Gmail Temporaires",
    "tempGmailPage.lead": "Générez instantanément des adresses Gmail jetables qui ressemblent et fonctionnent comme de vrais comptes Gmail. Protégez votre boîte de réception personnelle du spam et des messages indésirables.",
    "tempGmailPage.seoTitle1": "Fonctions Cachées de Confidentialité Gmail : L'Adressage Plus et l'Astuce du Point",
    "tempGmailPage.seoP1": "Saviez-vous que votre compte Gmail peut générer des adresses email illimitées sans créer de nouveaux comptes ? Gmail possède deux puissantes fonctionnalités intégrées que la plupart des utilisateurs ignorent : l'adressage plus (alias) et l'astuce du point (placement des points). Fire Temp Mail vous aide à exploiter ces fonctionnalités spécifiques à Gmail pour protéger votre vie privée et organiser votre boîte de réception.",
    "tempGmailPage.seoP2": "Ce ne sont pas des emails \"jetables\" d'un service tiers — ce sont des variations légitimes de votre véritable adresse Gmail qui sont livrées directement dans votre boîte de réception existante tout en vous permettant de suivre, filtrer et organiser les messages par source.",
    "tempGmailPage.plusTitle": "Comprendre l'Adressage Plus de Gmail (L'Astuce du \"+\")",
    "tempGmailPage.plusP1": "Gmail ignore tout ce qui suit le signe plus (+) dans votre adresse email. Si votre email est john.smith@gmail.com, toutes ces adresses sont livrées dans la même boîte :",
    "tempGmailPage.plusL1": "john.smith+shopping@gmail.com — Pour les sites d'achats en ligne",
    "tempGmailPage.plusL2": "john.smith+newsletters@gmail.com — Pour les abonnements aux newsletters",
    "tempGmailPage.plusL3": "john.smith+facebook@gmail.com — Pour l'inscription à Facebook",
    "tempGmailPage.plusL4": "john.smith+netflix@gmail.com — Pour l'essai de Netflix",
    "tempGmailPage.plusL5": "john.smith+spam@gmail.com — Pour les sites non fiables",
    "tempGmailPage.whyPlusTitle": "Pourquoi l'Adressage Plus est Puissant",
    "tempGmailPage.whyPlusP1": "1. Traquer les Vendeurs d'Email : Si vous vous inscrivez à un service avec votremail+serviceX@gmail.com et commencez à recevoir du spam à cette adresse, vous savez exactement qui a vendu votre email aux marketeurs.",
    "tempGmailPage.whyPlusP2": "2. Filtrage Automatique : Créez des filtres Gmail basés sur le label \"+\" pour organiser automatiquement les emails en dossiers, appliquer des étiquettes ou même supprimer automatiquement le spam de sources spécifiques.",
    "tempGmailPage.whyPlusP3": "3. Organiser les Inscriptions : Utilisez différents labels pour différentes catégories : +travail, +perso, +tests, +shopping. Voyez instantanément à quelle catégorie appartient chaque email.",
    "tempGmailPage.whyPlusP4": "4. Contourner les Restrictions \"Un Email Par Compte\" : Certains services (forums, concours, essais) n'autorisent qu'un compte par email. Utilisez l'adressage plus pour créer \"plusieurs\" adresses.",
    "tempGmailPage.dotTitle": "L'Astuce du Point Gmail : Le Placement des Points ne Compte Pas",
    "tempGmailPage.dotP1": "Gmail ignore complètement les points dans la partie nom d'utilisateur de votre adresse email. Cela signifie que johnsmith@gmail.com, john.smith@gmail.com, j.o.h.n.s.m.i.t.h@gmail.com sont tous livrés dans la même boîte de réception.",
    "tempGmailPage.dotUseTitle": "Comment Utiliser l'Astuce du Point",
    "tempGmailPage.dotUseP1": "Inscriptions Multi-Comptes : Si un site web n'autorise qu'un email par personne, vous pouvez inscrire plusieurs comptes en utilisant différents placements de points. Le site les voit comme des emails différents, mais Gmail les voit tous comme les vôtres.",
    "tempGmailPage.combineTitle": "Combiner l'Adressage Plus ET l'Astuce du Point",
    "tempGmailPage.combineP1": "Pour une flexibilité maximale, combinez les deux fonctionnalités : j.o.h.n.smith+netflix@gmail.com. Cela crée virtuellement des adresses uniques illimitées qui vont toutes dans votre seule boîte Gmail tout en offrant des capacités maximales de suivi et de filtrage.",
    "tempGmailPage.breachTitle": "Exemple Réel : Traquer les Fuites de Données",
    "tempGmailPage.breachP1": "Disons que vous vous inscrivez à \"ShoppingAppX\" avec votremail+shoppingappx@gmail.com. Six mois plus tard, vous recevez du spam à cette adresse exacte. Maintenant vous savez que ShoppingAppX :",
    "tempGmailPage.breachL1": "A vendu votre email à des marketeurs",
    "tempGmailPage.breachL2": "A subi une fuite de données",
    "tempGmailPage.breachL3": "Partage les emails avec des \"partenaires\"",
    "tempGmailPage.breachP2": "Vous pouvez maintenant créer un filtre Gmail pour supprimer automatiquement tout ce qui est envoyé à votremail+shoppingappx@gmail.com, bloquant efficacement cette source de spam sans affecter vos autres emails.",
    "tempGmailPage.filterTitle": "Comment Configurer des Filtres Gmail pour l'Adressage Plus",
    "tempGmailPage.filterP1": "Une fois que vous commencez à utiliser l'adressage plus, organisez automatiquement les emails entrants :",
    "tempGmailPage.filterL1": "Ouvrir les Paramètres Gmail : Cliquez sur l'icône d'engrenage → \"Voir tous les paramètres\"",
    "tempGmailPage.filterL2": "Aller à \"Filtres et adresses bloquées\" : Cliquez sur \"Créer un nouveau filtre\"",
    "tempGmailPage.filterL3": "Ajouter une Règle de Filtre : Dans le champ \"À\", entrez votremail+shopping@gmail.com",
    "tempGmailPage.filterL4": "Choisir l'Action : Appliquer le label \"Shopping\", ignorer la boîte de réception, marquer comme lu, transférer ou supprimer",
    "tempGmailPage.filterL5": "Enregistrer le Filtre : Cliquez sur \"Créer le filtre\" et c'est fait",
    "tempGmailPage.filterP2": "Désormais, chaque email envoyé à cette adresse est automatiquement organisé selon vos règles.",
    "tempGmailPage.limitTitle": "Limitations des Fonctionnalités Intégrées de Gmail",
    "tempGmailPage.limitP1": "Bien que puissantes, l'adressage plus et l'astuce du point de Gmail ont quelques limitations :",
    "tempGmailPage.limitL1": "Pas Vraiment Anonyme : Votre adresse Gmail de base reste visible. N'importe qui peut retirer le \"+label\" pour trouver votre vraie adresse.",
    "tempGmailPage.limitL2": "Certains Sites Bloquent le Signe + : Certains sites web rejettent les adresses email contenant des symboles \"+\".",
    "tempGmailPage.limitL3": "Pas de Protection contre Google : Google voit toujours toute votre activité. Ces astuces ne vous protègent pas de la collecte de données de Google.",
    "tempGmailPage.limitL4": "Impossible de Supprimer des Alias Individuels : Contrairement aux vrais emails jetables, vous ne pouvez pas \"brûler\" un alias s'il est compromis.",
    "tempGmailPage.limitL5": "Pas pour les Inscriptions à Haut Risque : Puisque votre vrai Gmail est toujours techniquement exposé, n'utilisez pas ces astuces pour des sites web non fiables. Utilisez Fire Temp Mail à la place.",
    "tempGmailPage.vsTitle": "Quand Utiliser les Astuces Gmail vs. les Vrais Emails Jetables",
    "tempGmailPage.useGmailTitle": "Utilisez l'Adressage Plus/Astuce du Point Gmail Quand :",
    "tempGmailPage.useGmailL1": "Vous voulez que les emails arrivent dans votre boîte principale",
    "tempGmailPage.useGmailL2": "Vous devez suivre quels services partagent/vendent votre email",
    "tempGmailPage.useGmailL3": "Vous voulez organiser les emails de différentes sources",
    "tempGmailPage.useGmailL4": "Le service est relativement fiable mais génère du spam",
    "tempGmailPage.useGmailL5": "Vous pourriez avoir besoin d'un accès à long terme au compte",
    "tempGmailPage.useDispTitle": "Utilisez les Emails Entièrement Jetables de Fire Temp Mail Quand :",
    "tempGmailPage.useDispL1": "Vous avez besoin d'un anonymat complet (sans lien avec votre vrai email)",
    "tempGmailPage.useDispL2": "Vous vous inscrivez sur des sites web non fiables ou risqués",
    "tempGmailPage.useDispL3": "Vérifications uniques que vous n'aurez plus jamais besoin",
    "tempGmailPage.useDispL4": "Tests pendant le développement sans remplir votre vraie boîte de réception",
    "tempGmailPage.useDispL5": "Services qui pourraient générer beaucoup de spam ou vendre des données de manière agressive",
    "tempGmailPage.tipsTitle": "Conseils de Confidentialité et Techniques Avancées Spécifiques à Gmail",
    "tempGmailPage.tip1Title": "1. Créer un Système de Filtres \"Brûleur\" dans Gmail",
    "tempGmailPage.tip1P1": "Configurez un filtre dédié pour tous les emails avec adressage plus :",
    "tempGmailPage.tip1L1": "Condition du filtre : to:votremail+*@gmail.com",
    "tempGmailPage.tip1L2": "Action : Appliquer le label \"Inscriptions Suivies\" et ignorer la boîte de réception",
    "tempGmailPage.tip1L3": "Résultat : Tous les emails avec adressage plus contournent votre boîte principale, la gardant propre",
    "tempGmailPage.tip2Title": "2. Utiliser des Conventions de Nommage Systématiques",
    "tempGmailPage.tip2P1": "Développez un système de labellisation cohérent :",
    "tempGmailPage.tip2L1": "+achat-[nomsite] — Sites d'achats",
    "tempGmailPage.tip2L2": "+news-[sujet] — Newsletters",
    "tempGmailPage.tip2L3": "+essai-[service] — Essais gratuits",
    "tempGmailPage.tip2L4": "+social-[plateforme] — Réseaux sociaux",
    "tempGmailPage.tip3Title": "3. Traquer les Sources de Fuites de Données",
    "tempGmailPage.tip3P1": "Quand vous recevez du spam ou des emails de phishing, vérifiez le champ \"À\". S'il affiche votremail+sitespecifique@gmail.com, vous avez identifié la source de la fuite ou de la violation de données.",
    "tempGmailPage.ctaTitle": "Commencez à Utiliser les Fonctions de Confidentialité Gmail Aujourd'hui",
    "tempGmailPage.ctaP1": "L'adressage plus et l'astuce du point de Gmail sont des fonctionnalités entièrement gratuites et intégrées qui fonctionnent immédiatement avec votre compte Gmail existant. Pas d'inscription, pas de service tiers, pas de risque. Commencez à protéger votre vie privée et à organiser votre boîte de réception en exploitant ces puissantes capacités spécifiques à Gmail.",
    "tempGmailPage.ctaP2": "Pour les situations nécessitant un anonymat complet : Utilisez les vraies adresses email jetables de Fire Temp Mail sur la page principale. Pour tout le reste, utilisez les fonctions de confidentialité intégrées de Gmail expliquées ici.",
    "burnerEmailPage.h1": "Générateur d'Email Brûleur Gratuit – Créez des Adresses Jetables Instantanément",
    "burnerEmailPage.lead": "Générez instantanément des adresses email anonymes. Parfaites pour protéger votre vraie identité en ligne — pas d'inscription, pas de données personnelles requises.",
    "burnerEmailPage.seoTitle": "Qu'est-ce qu'un Email Brûleur et Pourquoi en Avez-Vous Besoin ?",
    "burnerEmailPage.seoP1": "Un email brûleur est une adresse email jetable et temporaire qui vous permet d'envoyer ou de recevoir des messages sans révéler votre vraie identité. Contrairement à un compte email régulier que vous conservez pendant des années, un email brûleur est délibérément éphémère et anonyme — conçu pour être utilisé une fois puis jeté.",
    "burnerEmailPage.seoP2": "Le terme \"brûleur\" vient des \"téléphones brûleurs\" — des téléphones prépayés et intraçables utilisés pour la communication temporaire. Les emails brûleurs fonctionnent de la même manière : ils créent une couche de séparation entre votre vraie identité et le monde en ligne.",
    "burnerEmailPage.howTitle": "Comment Fonctionnent les Emails Brûleurs",
    "burnerEmailPage.howP1": "Les services d'email brûleur comme Fire Temp Mail génèrent une adresse email aléatoire au moment où vous visitez le site web. Pas besoin de créer un compte, d'entrer des informations personnelles ou de vérifier quoi que ce soit. Voici comment ça marche :",
    "burnerEmailPage.howL1": "Génération Instantanée : Visitez le site web et recevez immédiatement une adresse email aléatoire et anonyme.",
    "burnerEmailPage.howL2": "Recevoir des Emails : Utilisez l'adresse pour vous inscrire à des services, recevoir des codes de vérification ou accepter des messages ponctuels.",
    "burnerEmailPage.howL3": "Aucun Lien d'Identité : L'adresse n'a aucune connexion avec votre vrai nom, numéro de téléphone ou email permanent.",
    "burnerEmailPage.howL4": "Expiration Automatique : Après une courte période (habituellement 24 heures), l'adresse email et tous les messages associés sont supprimés définitivement.",
    "burnerEmailPage.howL5": "Adresses Illimitées : Générez autant d'adresses brûleurs que nécessaire. Chacune est complètement indépendante.",
    "burnerEmailPage.usesTitle": "Principaux Cas d'Utilisation des Emails Brûleurs",
    "burnerEmailPage.use1Title": "1. Inscriptions et Abonnements sur les Sites Web",
    "burnerEmailPage.use1P": "La plupart des sites web exigent une adresse email pour créer un compte. Les emails brûleurs vous permettent de vous inscrire sans risquer d'inonder votre vraie boîte de réception d'emails promotionnels et de newsletters.",
    "burnerEmailPage.use2Title": "2. Inscriptions aux Essais Gratuits",
    "burnerEmailPage.use2P": "De nombreux services offrent des essais gratuits limités dans le temps mais nécessitent une adresse email. Utilisez un email brûleur pour tester le service sans risque.",
    "burnerEmailPage.use3Title": "3. Achats en Ligne et Coupons",
    "burnerEmailPage.use3P": "Les sites de vente au détail exigent souvent un email pour le paiement ou pour débloquer des réductions. Un email brûleur empêche le spam post-achat tout en vous donnant accès aux offres.",
    "burnerEmailPage.use4Title": "4. Connexion Wi-Fi Public",
    "burnerEmailPage.use4P": "Les cafés, aéroports et hôtels exigent fréquemment une adresse email pour accéder à leurs réseaux Wi-Fi. Utilisez un email brûleur au lieu de votre email personnel.",
    "burnerEmailPage.use5Title": "5. Téléchargement de Ressources",
    "burnerEmailPage.use5P": "E-books, livres blancs, modèles et autres ressources téléchargeables sont généralement derrière un formulaire demandant un email. Les emails brûleurs vous permettent d'accéder au contenu sans vous abonner à des listes de diffusion indésirables.",
    "burnerEmailPage.use6Title": "6. Inscriptions aux Forums et Communautés",
    "burnerEmailPage.use6P": "Les forums, communautés type Reddit et tableaux de discussion exigent souvent des emails pour créer des comptes. Utilisez un email brûleur pour participer anonymement.",
    "burnerEmailPage.use7Title": "7. Tests de Développement et QA",
    "burnerEmailPage.use7P": "Les développeurs et testeurs de logiciels ont constamment besoin d'adresses email fraîches pour tester les flux d'inscription, les systèmes de vérification et les fonctionnalités de notification.",
    "burnerEmailPage.benefitsTitle": "Avantages de l'Utilisation des Emails Brûleurs",
    "burnerEmailPage.ben1": "Protection de la Vie Privée : Votre vrai email reste caché. Personne ne peut remonter un email brûleur jusqu'à vous.",
    "burnerEmailPage.ben2": "Prévention du Spam : Tout le spam va à l'adresse brûleur, gardant votre vraie boîte de réception propre pour toujours.",
    "burnerEmailPage.ben3": "Sécurité contre les Fuites de Données : Si le service auquel vous vous êtes inscrit est piraté, votre vrai email ne sera pas dans la liste des utilisateurs fuités.",
    "burnerEmailPage.ben4": "Aucune Gestion de Compte : Pas de mots de passe à retenir. Pas de comptes supplémentaires à maintenir.",
    "burnerEmailPage.ben5": "Instantané et Gratuit : Pas d'inscription nécessaire. Pas de coût. Visitez, générez et utilisez.",
    "burnerEmailPage.vsTitle": "Email Brûleur vs. Email Régulier vs. Alias d'Email",
    "burnerEmailPage.vsP1": "Email Régulier (Gmail, Outlook) : Permanent, lié à votre identité, utilisé pour la communication à long terme. Vulnérable au spam et aux fuites de données.",
    "burnerEmailPage.vsP2": "Alias d'Email (+tags, points) : Variations de votre vrai email qui sont toujours livrées dans votre boîte de réception. Utiles pour l'organisation mais ne cachent pas votre vraie adresse.",
    "burnerEmailPage.vsP3": "Email Brûleur (Fire Temp Mail) : Complètement séparé de votre vraie identité. Temporaire, anonyme, auto-supprimé. Le meilleur pour la confidentialité et l'utilisation ponctuelle.",
    "eduEmailPage.h1": "Générateur d'Email EDU Gratuit – Créez une Boîte .EDU Jetable Instantanément",
    "eduEmailPage.lead": "Générez des emails .EDU avec notre générateur d'Email EDU gratuit. Parfait pour les inscriptions, tests, réductions étudiantes et plus — sans exposer votre vraie boîte de réception au spam.",
    "eduEmailPage.seoTitle": "Meilleures Réductions Étudiantes et Avantages Email .EDU",
    "eduEmailPage.seoP1": "Les réductions étudiantes peuvent vous faire économiser des milliers de dollars par an sur les logiciels, services de streaming et ressources d'apprentissage.",
    "eduEmailPage.discountsTitle": "Meilleures Réductions Étudiantes Nécessitant une Vérification .EDU",
    "eduEmailPage.spotifyTitle": "Spotify Premium Étudiant - 5,99$/mois (50% de réduction)",
    "eduEmailPage.spotifyP1": "Prix Normal : 10,99$/mois | Économie Étudiante : 60$/an",
    "eduEmailPage.spotifyP2": "Inclut Hulu (avec publicités) et SHOWTIME sans frais supplémentaires. Vérifié via SheerID avec votre email .EDU.",
    "eduEmailPage.amazonTitle": "Amazon Prime Étudiant - 7,49$/mois",
    "eduEmailPage.amazonP1": "Prix Normal : 14,99$/mois | Économie Étudiante : 90$/an + essai GRATUIT de 6 mois",
    "eduEmailPage.amazonP2": "Tous les avantages Prime : Livraison gratuite en 2 jours, Prime Video, Prime Music, stockage photo illimité et plus.",
    "eduEmailPage.adobeTitle": "Adobe Creative Cloud - 60% de réduction",
    "eduEmailPage.adobeP1": "Prix Normal : 59,99$/mois | Prix Étudiant : 19,99$/mois | Économie : 480$/an",
    "eduEmailPage.adobeP2": "Suite complète : Photoshop, Illustrator, Premiere Pro, After Effects, InDesign et plus de 20 applications.",
    "eduEmailPage.appleTitle": "Apple Music Étudiant - 5,99$/mois",
    "eduEmailPage.appleP1": "Prix Normal : 10,99$/mois | Économie Étudiante : 60$/an",
    "eduEmailPage.appleP2": "Catalogue complet Apple Music plus abonnement Apple TV+ gratuit inclus.",
    "eduEmailPage.githubTitle": "GitHub Student Developer Pack - GRATUIT",
    "eduEmailPage.githubP1": "Coût Normal : 200$+/an en outils | Prix Étudiant : Complètement GRATUIT",
    "eduEmailPage.githubP2": "GitHub Pro, nom de domaine gratuit, crédits cloud, outils CI/CD et plus de 20 outils et services pour développeurs.",
    "bestTempMailPage.h1": "Meilleur Temp Mail – Service n°1 d'Email Temporaire Jetable Gratuit",
    "bestTempMailPage.lead": "Le meilleur service de mail temporaire en ligne. Générez des adresses email jetables instantanément — sans inscription, sans informations personnelles nécessaires. Privé, rapide et gratuit.",
    "bestTempMailPage.seoTitle": "Pourquoi Fire Temp Mail est le Meilleur Service d'Email Temporaire",
    "bestTempMailPage.seoP1": "Avec des dizaines de services d'email temporaire disponibles en ligne, choisir le bon est important. Fire Temp Mail se distingue comme le meilleur service de temp mail pour plusieurs raisons clés.",
    "bestTempMailPage.comparison": "Comparaison des Fonctionnalités avec d'Autres Services",
    "bestTempMailPage.whyBestTitle": "Ce Qui Nous Rend les Meilleurs",
    "bestTempMailPage.whyBestP1": "Fire Temp Mail combine vitesse, confidentialité et simplicité d'une manière qu'aucun autre service d'email temporaire ne propose.",
    "bestTempMailPage.feature1": "Génération Instantanée : Pas d'attente, pas d'inscription. Visitez la page et votre email temporaire est prêt immédiatement.",
    "bestTempMailPage.feature2": "Domaines Multiples : Choisissez parmi plusieurs domaines email différents pour répondre à vos besoins.",
    "bestTempMailPage.feature3": "Adresses Style Gmail : Obtenez des adresses temporaires type Gmail qui fonctionnent partout.",
    "bestTempMailPage.feature4": "Alias Personnalisés : Créez des adresses temporaires personnalisées pour l'organisation.",
    "bestTempMailPage.feature5": "Boîte Auto-Actualisée : Les nouveaux emails apparaissent automatiquement sans actualisation manuelle.",
    "bestTempMailPage.feature6": "Confidentialité d'Abord : Pas de suivi, pas de journalisation, pas de collecte de données.",
    "gmailGeneratorPage.h1": "Générateur Gmail Gratuit – Créez des Adresses Gmail Temporaires Instantanément",
    "gmailGeneratorPage.lead": "Générez une adresse Gmail temporaire gratuite avec notre Générateur Gmail. Accédez à une boîte Gmail jetable instantanément — sans inscription, sans données personnelles. Restez anonyme en ligne.",
    "gmailGeneratorPage.seoTitle": "Comment Fonctionne le Générateur Gmail",
    "gmailGeneratorPage.seoP1": "Notre Générateur Gmail crée des adresses jetables type Gmail qui fonctionnent comme de vrais comptes Gmail. Utilisez-les pour les inscriptions, vérifications et tests sans exposer votre vraie adresse Gmail.",
    "gmailGeneratorPage.howItWorksTitle": "Comment Ça Marche",
    "gmailGeneratorPage.howItWorksP1": "1. Visitez Fire Temp Mail et sélectionnez l'option Gmail. 2. Une adresse temporaire type Gmail est générée instantanément. 3. Utilisez-la pour toute inscription ou vérification en ligne. 4. Recevez des emails en temps réel dans votre boîte privée. 5. L'adresse expire automatiquement après 24 heures.",
    "temporaryGmailPage.h1": "Gmail Temporaire – Adresses Gmail Jetables Gratuites",
    "temporaryGmailPage.lead": "Obtenez une adresse Gmail temporaire gratuite qui fonctionne exactement comme un vrai compte Gmail. Parfaite pour les inscriptions, vérifications et la protection de votre boîte principale contre le spam.",
    "temporaryGmailPage.seoTitle": "Les Adresses Gmail Temporaires Expliquées",
    "temporaryGmailPage.seoP1": "Une adresse Gmail temporaire est un email jetable de courte durée qui ressemble et fonctionne comme un vrai compte Gmail. Elle vous permet de recevoir des emails de vérification, de vous inscrire à des services et de maintenir la confidentialité sans exposer votre email permanent.",
    "temporaryGmailPage.benefitsTitle": "Avantages du Gmail Temporaire",
    "temporaryGmailPage.benefitsP1": "Protégez votre vrai Gmail du spam, évitez les fuites de données et inscrivez-vous à des services anonymement. Le tout sans inscription requise.",
    "tempMailEduPage.h1": "Temp Mail EDU – Générateur d'Email .EDU Temporaire Gratuit",
    "tempMailEduPage.lead": "Générez instantanément des adresses email .EDU temporaires. Accédez aux réductions étudiantes, ressources éducatives et outils en ligne avec une boîte .EDU jetable.",
    "tempMailEduPage.seoTitle": "Utiliser Temp Mail à des Fins Éducatives",
    "tempMailEduPage.seoP1": "Les emails .EDU temporaires peuvent vous aider à accéder aux ressources éducatives, tester les systèmes de vérification étudiante et explorer les fonctionnalités de plateformes conçues pour la communauté académique.",
    "tenMinuteMailPage.h1": "10 Minute Mail – Email Jetable Rapide qui Expire Vite",
    "tenMinuteMailPage.lead": "Besoin d'un email jetable rapide ? Notre 10 Minute Mail vous donne une adresse jetable instantanée qui s'auto-supprime. Parfait pour les inscriptions et vérifications ponctuelles.",
    "tenMinuteMailPage.seoTitle": "Qu'est-ce que 10 Minute Mail et Comment Ça Marche ?",
    "tenMinuteMailPage.seoP1": "10 Minute Mail est un type de service d'email jetable qui vous fournit une adresse email temporaire qui dure seulement 10 minutes. C'est le moyen le plus rapide d'obtenir un email jetable pour des inscriptions et vérifications rapides.",
    "tenMinuteMailPage.howTitle": "Comment Fonctionne 10 Minute Mail",
    "tenMinuteMailPage.howP1": "Visitez la page et obtenez une adresse email instantanée. Utilisez-la pour toute inscription ou vérification. L'adresse et tous les emails sont supprimés définitivement après 10 minutes.",
    "tenMinuteMailPage.whyTitle": "Pourquoi Utiliser 10 Minute Mail ?",
    "tenMinuteMailPage.whyP1": "Parfois vous n'avez pas besoin d'une adresse email pour longtemps. Les inscriptions rapides, les vérifications ponctuelles et le téléchargement de contenu protégé sont tous des cas d'utilisation parfaits pour 10 minute mail.",
    "tenMinuteMailPage.vsTitle": "10 Minute Mail vs Temp Mail Régulier",
    "tenMinuteMailPage.vsP1": "10 Minute Mail est plus rapide et conçu pour des cas d'utilisation ultra-rapides. L'email temporaire régulier (comme Fire Temp Mail) dure plus longtemps (jusqu'à 24 heures) et est meilleur pour les tests, le développement et les situations où vous avez besoin de l'email pendant plus de quelques minutes.",
    "temporaryEmailGenPage.h1": "Générateur d'Email Temporaire – Créez des Adresses Email Jetables Gratuitement",
    "temporaryEmailGenPage.lead": "Générez des adresses email temporaires instantanément. Notre Générateur d'Email Temporaire fournit des boîtes jetables gratuites — parfaites pour protéger votre vie privée en ligne.",
    "temporaryEmailGenPage.seoTitle": "Comment Fonctionnent les Générateurs d'Email Temporaire",
    "temporaryEmailGenPage.seoP1": "Un générateur d'email temporaire crée des adresses email anonymes de courte durée à la demande. Ces adresses fonctionnent comme des emails réguliers mais expirent automatiquement, gardant votre vraie identité protégée.",
    "fireMailPage.h1": "Fire Mail – Service d'Email Temporaire Rapide et Gratuit",
    "fireMailPage.lead": "Fire Mail fournit des adresses email temporaires instantanées pour une confidentialité en ligne complète. Sans inscription, sans données personnelles — simplement un email jetable pur et chiffré.",
    "fireMailPage.seoTitle": "Pourquoi Choisir Fire Mail pour l'Email Temporaire",
    "fireMailPage.seoP1": "Fire Mail est conçu pour la vitesse, la confidentialité et la fiabilité. Notre service d'email temporaire génère des adresses jetables instantanément, avec des mises à jour de boîte de réception en temps réel et un nettoyage automatique.",
    "gmailnatorPage.h1": "Alternative à Gmailnator – Générateur Gmail Temporaire Gratuit",
    "gmailnatorPage.lead": "Vous cherchez une alternative à Gmailnator ? Fire Temp Mail offre la même fonctionnalité avec une meilleure confidentialité, des performances plus rapides et une livraison d'email plus fiable.",
    "gmailnatorPage.seoTitle": "Meilleure Alternative à Gmailnator en 2024",
    "gmailnatorPage.seoP1": "Gmailnator était un service populaire pour générer des adresses Gmail temporaires. Fire Temp Mail offre la même fonctionnalité avec une fiabilité améliorée, de meilleures protections de confidentialité et une expérience utilisateur moderne.",
    "about.metaTitle": "À Propos de Fire Temp Mail - Notre Mission et Histoire",
    "about.metaDescription": "Découvrez Fire Temp Mail — un service d'email temporaire gratuit protégeant votre vie privée en ligne. Notre mission et nos valeurs.",
    "about.title": "À Propos de Fire Temp Mail",
    "about.subtitle": "Protéger votre vie privée numérique, un email temporaire à la fois",
    "about.missionTitle": "Notre Mission",
    "about.missionP1": "Fire Temp Mail a été créé pour résoudre un problème simple mais critique : l'érosion de la vie privée en ligne. Chaque jour, des millions de personnes sont obligées de fournir leurs adresses email personnelles pour accéder à des services, s'inscrire à des essais ou télécharger des ressources — ce qui entraîne souvent une boîte de réception inondée de spam et d'emails marketing indésirables.",
    "about.missionP2": "Nous croyons que votre adresse email est personnelle. Vous ne devriez pas avoir à sacrifier votre vie privée ou compromettre la sécurité de votre boîte de réception juste pour accéder à des services en ligne. C'est pourquoi nous avons construit Fire Temp Mail : un service d'email temporaire entièrement gratuit et sans inscription qui met votre vie privée en premier.",
    "about.whatWeDoTitle": "Ce Que Nous Faisons",
    "about.whatWeDoP1": "Fire Temp Mail fournit des adresses email instantanées, anonymes et jetables que n'importe qui peut utiliser — sans inscription requise. Que vous ayez besoin d'un email temporaire pour une inscription ponctuelle, pour éviter le spam de newsletters ou pour protéger votre vraie identité en ligne, nous avons la solution.",
    "about.whatWeDo1": "Génération d'email instantanée — visitez simplement et obtenez une adresse email fonctionnelle",
    "about.whatWeDo2": "Boîte de réception en temps réel — recevez des emails instantanément dans votre navigateur",
    "about.whatWeDo3": "Domaines multiples — choisissez parmi plusieurs domaines email disponibles",
    "about.whatWeDo4": "Alias personnalisés — créez des adresses temporaires personnalisées",
    "about.whatWeDo5": "Adresses style Gmail — obtenez des adresses temporaires type Gmail",
    "about.whatWeDo6": "Auto-suppression — les emails sont automatiquement nettoyés pour une confidentialité totale",
    "about.whyTitle": "Pourquoi Fire Temp Mail ?",
    "about.whyP1": "Dans un monde où les fuites de données, le spam et le marketing non sollicité sont des problèmes quotidiens, Fire Temp Mail offre une solution simple mais puissante.",
    "about.why1": "Gratuit pour toujours — pas de coûts cachés, d'abonnements ou de restrictions premium",
    "about.why2": "Sans inscription — commencez à utiliser instantanément, pas de compte nécessaire",
    "about.why3": "Confidentialité d'abord — nous ne suivons, ne vendons ni ne monétisons vos données",
    "about.why4": "Ouvert et transparent — service direct sans artifices",
    "about.why5": "Rapide et fiable — construit sur une infrastructure moderne pour la vitesse",
    "about.valuesTitle": "Nos Valeurs",
    "about.value1Title": "La Confidentialité Avant Tout",
    "about.value1Text": "Nous croyons que la vie privée est un droit fondamental. Notre service est conçu de zéro pour protéger la vôtre.",
    "about.value2Title": "Simplicité",
    "about.value2Text": "Obtenir un email temporaire devrait être sans effort. Visitez notre site, obtenez un email, utilisez-le. C'est tout.",
    "about.value3Title": "Transparence",
    "about.value3Text": "Pas d'intentions cachées. Nous sommes francs sur le fonctionnement de notre service et comment nous le maintenons.",
    "about.value4Title": "Accessibilité",
    "about.value4Text": "Tout le monde mérite la confidentialité. C'est pourquoi Fire Temp Mail est gratuit pour tous, partout.",
    "about.futureTitle": "Regard vers l'Avenir",
    "about.futureP1": "Nous améliorons constamment Fire Temp Mail pour mieux servir nos utilisateurs. Notre feuille de route inclut des fonctionnalités de sécurité améliorées, plus d'options de domaines, une expérience mobile améliorée et des outils supplémentaires pour protéger votre vie privée numérique.",
    "about.futureP2": "Merci de faire confiance à Fire Temp Mail pour votre vie privée en ligne. Ensemble, nous construisons un internet plus sûr et plus privé — un email temporaire à la fois.",
    "about.contactTitle": "Nous Contacter",
    "about.contactP1": "Vous avez des questions, des commentaires ou vous voulez simplement dire bonjour ? Nous serions ravis de vous entendre.",
    "about.contactEmail": "Envoyez-nous un email à",
    "about.contactLink": "Ou visitez notre page de Contact"
}

for dotpath, value in t.items():
    set_nested(locale, dotpath, value)

with open(os.path.join(BASE, 'fr.json'), 'w') as f:
    json.dump(locale, f, indent=2, ensure_ascii=False)
print(f"Updated fr.json with {len(t)} new keys")
