#!/usr/bin/env python3
"""Generate Portuguese (PT) translations for all missing keys."""
import json, os

BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'src/lib/i18n/locales')

def set_nested(obj, dotpath, value):
    parts = dotpath.split('.')
    for part in parts[:-1]:
        if part not in obj: obj[part] = {}
        obj = obj[part]
    obj[parts[-1]] = value

with open(os.path.join(BASE, 'pt.json'), 'r') as f:
    locale = json.load(f)

t = {
    "email.generateNew": "Gerar Novo",
    "email.changeDomain": "Mudar Domínio",
    "email.refreshPage": "Atualizar Página",
    "email.generateCustomEmail": "Gerar Email Personalizado",
    "email.waitingForEmails": "Aguardando emails recebidos",
    "email.refreshStopped": "Atualização automática parada",
    "email.inboxEmpty": "Sua caixa de entrada está vazia",
    "email.domain": "Domínio",
    "email.gmail": "Gmail",
    "email.googlemail": "GoogleMail",
    "email.copyToClipboard": "Copiar para a área de transferência",
    "email.useCustomAlias2": "Usar alias personalizado",
    "email.changeDomain2": "Mudar domínio",
    "email.refreshPage2": "Atualizar página",
    "email.scenario": "Cenário:",
    "email.solution": "Solução:",
    "email.challenge": "Desafio:",
    "email.testingWorkflow": "Fluxo de teste:",
    "email.testScenarios": "Cenários de teste:",
    "email.perfectFor": "Perfeito para:",
    "email.important": "IMPORTANTE:",
    "email.neverUse": "NUNCA use emails temporários para:",
    "emailGeneratorPage.h1": "Fire Temp Mail – Seu Gerador de Email Descartável Grátis",
    "emailGeneratorPage.lead": "Gere instantaneamente um endereço de email descartável. Mantenha seu email real privado e sua caixa de entrada limpa de mensagens indesejadas e spam.",
    "emailGeneratorPage.seoTitle": "Gerador de Email para Desenvolvedores e Testes QA",
    "emailGeneratorPage.seoDesc": "Gerador de email temporário profissional projetado especificamente para desenvolvedores de software, engenheiros QA e testadores de automação. Gere endereços de email descartáveis ilimitados para testar fluxos de cadastro, sistemas de verificação de email, redefinição de senhas e lógica de notificação — sem gerenciar contas de teste ou preencher caixas de entrada pessoais.",
    "emailGeneratorPage.whyTitle": "Por Que Desenvolvedores Precisam de Emails Descartáveis para Testes",
    "emailGeneratorPage.whyP1": "Testar funcionalidades dependentes de email é essencial, mas doloroso. Você precisa verificar o cadastro de usuários, links de confirmação por email, fluxos de redefinição de senha e sistemas de notificação — mas criar dezenas de contas de email reais é lento, insustentável e enche sua caixa de entrada.",
    "emailGeneratorPage.whyP2": "Fire Temp Mail fornece endereços de email instantâneos e descartáveis projetados especificamente para testes de software. Gere emails temporários ilimitados para testar os fluxos de email da sua aplicação sem gerenciar contas de teste ou lidar com restrições de provedores de email.",
    "emailGeneratorPage.painPointsTitle": "Problemas Comuns de Desenvolvedores (Resolvidos)",
    "emailGeneratorPage.pp1": "Criar contas de teste Gmail/Outlook manualmente → Gere emails ilimitados instantaneamente",
    "emailGeneratorPage.pp2": "Gerenciar senhas para múltiplas contas de teste → Sem credenciais necessárias",
    "emailGeneratorPage.pp3": "Limpar dados de teste antigos → Auto-exclusão após 24 horas",
    "emailGeneratorPage.pp4": "Provedores de email bloqueando cadastros automáticos → Domínios reais que funcionam em todos os lugares",
    "emailGeneratorPage.pp5": "Testar cenários multi-usuário → Endereços únicos ilimitados sob demanda",
    "emailGeneratorPage.pp6": "Pipelines CI/CD precisando de emails frescos → Geração sem configuração",
    "emailGeneratorPage.uc1Title": "1. Teste de Cadastro de Usuário e Verificação de Email",
    "emailGeneratorPage.uc1P1": "Sua aplicação requer verificação de email durante o cadastro. Você precisa testar que os emails de verificação chegam, os links funcionam corretamente, os tokens expiram adequadamente e os casos limite são tratados.",
    "emailGeneratorPage.uc1P2": "Gere um email temporário → Cadastre-se no seu app → Verifique a caixa de entrada para o email de verificação (chega em segundos) → Extraia o link/token de verificação → Complete a verificação → Teste casos limite (tokens expirados, verificações duplicadas).",
    "emailGeneratorPage.uc2Title": "2. Teste de Fluxo de Redefinição de Senha",
    "emailGeneratorPage.uc2P1": "Teste exaustivamente sua funcionalidade de redefinição de senha gerando contas de teste com emails temporários, acionando o fluxo de esqueci minha senha, recebendo emails de redefinição instantaneamente e verificando a segurança de tokens e lógica de expiração.",
    "emailGeneratorPage.uc2P2": "Solicitações de redefinição válidas, tokens expirados, múltiplas tentativas de redefinição, endereços de email inválidos, limitação de taxa e segurança entre contas.",
    "emailGeneratorPage.uc3Title": "3. Testes Multi-Usuário e Baseados em Papéis",
    "emailGeneratorPage.uc3P1": "Testar aplicações com diferentes papéis de usuário (admin, moderador, usuário) ou sistemas multi-tenant requer múltiplos endereços de email únicos. Gere emails temporários distintos para cada usuário de teste sem o trabalho de gerenciar contas reais.",
    "emailGeneratorPage.uc4Title": "4. Teste do Sistema de Notificação por Email",
    "emailGeneratorPage.uc4P1": "Se sua aplicação envia emails transacionais (confirmações de pedido, alertas, lembretes, atualizações de status), use emails temporários para verificar que os emails são acionados pelos eventos corretos, a personalização é renderizada corretamente, o formato HTML/CSS é exibido corretamente e os links funcionam como esperado.",
    "emailGeneratorPage.uc5Title": "5. Testes Automatizados e Integração CI/CD",
    "emailGeneratorPage.uc5P1": "Seu pipeline CI/CD executa testes E2E automatizados que envolvem fluxos de trabalho baseados em email. Cada execução de teste precisa de endereços de email frescos e únicos.",
    "emailGeneratorPage.uc5P2": "Gere emails temporários programaticamente ou use padrões de nomes consistentes para criar endereços únicos para cada execução de teste sem intervenção manual. Perfeito para suítes de teste Playwright, Cypress ou Selenium.",
    "emailGeneratorPage.uc6Title": "6. Testes de Integração com Serviços de Email de Terceiros",
    "emailGeneratorPage.uc6P1": "Testar integrações com SendGrid, Mailgun, AWS SES, Postmark ou outros provedores de serviços de email requer endereços de destinatários reais para verificar a entrega bem-sucedida de email, eventos de webhook, lógica de tratamento de rejeição, renderização de templates e autenticação SPF/DKIM.",
    "emailGeneratorPage.featuresTitle": "Funcionalidades para Desenvolvedores",
    "emailGeneratorPage.f1": "Sem Configuração: Sem chaves API, sem autenticação, sem criação de conta. Visite a página, obtenha um endereço de email, comece a testar.",
    "emailGeneratorPage.f2": "Recebimento de Email em Tempo Real: Os emails aparecem na caixa de entrada em segundos. Sem atrasos de polling, sem processamento em lotes.",
    "emailGeneratorPage.f3": "Acesso Completo ao Email: Veja o conteúdo completo do email incluindo corpo HTML, alternativa de texto simples, cabeçalhos de email, informações do remetente e anexos.",
    "emailGeneratorPage.f4": "Aliases Personalizados para Organização: Use endereços de email descritivos que mapeiam para casos de teste específicos.",
    "emailGeneratorPage.f5": "Limpeza Automática: Os emails são auto-excluídos após 24 horas. Sem limpeza manual, sem gerenciamento de credenciais, sem carga de manutenção.",
    "emailGeneratorPage.securityTitle": "Lembrete de Segurança para Desenvolvedores",
    "emailGeneratorPage.securityWarn": "Os emails temporários são públicos e inseguros. Use-os APENAS para ambientes de desenvolvimento, staging/QA com dados de teste, bancos de dados de teste isolados e testes de integração com APIs mock/teste.",
    "emailGeneratorPage.securityNever": "NUNCA use emails temporários para: Sistemas de produção, dados de usuários reais, testes de pagamento (mesmo em sandbox), informações sensíveis ou credenciais de bancos de dados de produção.",
    "emailGeneratorPage.startTitle": "Comece a Testar Agora",
    "emailGeneratorPage.startP1": "Pare de perder tempo gerenciando contas de email de teste. Gere emails temporários ilimitados instantaneamente e concentre-se no que importa — construir e testar software excelente. Sem cadastro, sem custo, sem complicação.",
    "emailGeneratorPage.startP2": "Desenvolvedores frontend, engenheiros backend, testadores QA, engenheiros DevOps, especialistas em automação e qualquer pessoa construindo funcionalidades dependentes de email.",
    "tempGmailPage.h1": "Temp Gmail - Criar Endereços Gmail Temporários",
    "tempGmailPage.lead": "Gere instantaneamente endereços Gmail descartáveis que parecem e funcionam como contas Gmail reais. Proteja sua caixa de entrada pessoal do spam e mensagens indesejadas.",
    "tempGmailPage.seoTitle1": "Funções Ocultas de Privacidade do Gmail: Plus-Addressing e o Truque do Ponto",
    "tempGmailPage.seoP1": "Você sabia que sua conta Gmail pode gerar endereços de email ilimitados sem criar novas contas? O Gmail tem duas poderosas funcionalidades integradas que a maioria dos usuários desconhece: plus-addressing (aliases) e o truque do ponto (posicionamento de pontos). Fire Temp Mail ajuda você a aproveitar essas funcionalidades específicas do Gmail para proteger sua privacidade e organizar sua caixa de entrada.",
    "tempGmailPage.seoP2": "Estes não são emails \"descartáveis\" de um serviço terceiro — são variações legítimas do seu endereço Gmail real que são entregues diretamente na sua caixa de entrada existente enquanto permitem rastrear, filtrar e organizar mensagens por fonte.",
    "tempGmailPage.plusTitle": "Entendendo o Plus-Addressing do Gmail (O Truque do \"+\")",
    "tempGmailPage.plusP1": "O Gmail ignora tudo após o sinal de mais (+) no seu endereço de email. Se seu email é john.smith@gmail.com, todos estes são entregues na mesma caixa de entrada:",
    "tempGmailPage.plusL1": "john.smith+shopping@gmail.com — Para sites de compras online",
    "tempGmailPage.plusL2": "john.smith+newsletters@gmail.com — Para assinaturas de newsletters",
    "tempGmailPage.plusL3": "john.smith+facebook@gmail.com — Para cadastro no Facebook",
    "tempGmailPage.plusL4": "john.smith+netflix@gmail.com — Para teste do Netflix",
    "tempGmailPage.plusL5": "john.smith+spam@gmail.com — Para sites não confiáveis",
    "tempGmailPage.whyPlusTitle": "Por Que o Plus-Addressing é Poderoso",
    "tempGmailPage.whyPlusP1": "1. Rastrear Vendedores de Email: Se você se cadastra em um serviço com seunome+servicoX@gmail.com e começa a receber spam nesse endereço, você sabe exatamente quem vendeu seu email para os marketeiros.",
    "tempGmailPage.whyPlusP2": "2. Filtragem Automática: Crie filtros do Gmail baseados no rótulo \"+\" para organizar automaticamente os emails em pastas, aplicar etiquetas ou até mesmo auto-excluir spam de fontes específicas.",
    "tempGmailPage.whyPlusP3": "3. Organizar Cadastros: Use diferentes rótulos para diferentes categorias: +trabalho, +pessoal, +testes, +compras. Veja instantaneamente a qual categoria cada email pertence.",
    "tempGmailPage.whyPlusP4": "4. Evitar Restrições de \"Um Email Por Conta\": Alguns serviços (fóruns, concursos, testes) só permitem uma conta por email. Use plus-addressing para criar \"múltiplos\" endereços.",
    "tempGmailPage.dotTitle": "O Truque do Ponto do Gmail: A Posição dos Pontos Não Importa",
    "tempGmailPage.dotP1": "O Gmail ignora completamente os pontos na parte do nome de usuário do seu endereço de email. Isso significa que johnsmith@gmail.com, john.smith@gmail.com, j.o.h.n.s.m.i.t.h@gmail.com todos são entregues na mesma caixa de entrada.",
    "tempGmailPage.dotUseTitle": "Como Usar o Truque do Ponto",
    "tempGmailPage.dotUseP1": "Cadastros em Múltiplas Contas: Se um site permite apenas um email por pessoa, você pode cadastrar múltiplas contas usando diferentes posições de pontos. O site os vê como emails diferentes, mas o Gmail vê todos como seus.",
    "tempGmailPage.combineTitle": "Combinando Plus-Addressing E o Truque do Ponto",
    "tempGmailPage.combineP1": "Para máxima flexibilidade, combine ambas as funcionalidades: j.o.h.n.smith+netflix@gmail.com. Isso cria praticamente endereços únicos ilimitados que todos vão para sua única caixa de entrada do Gmail enquanto fornecem capacidades máximas de rastreamento e filtragem.",
    "tempGmailPage.breachTitle": "Exemplo Real: Rastrear Vazamentos de Dados",
    "tempGmailPage.breachP1": "Digamos que você se cadastra no \"ShoppingAppX\" usando seunome+shoppingappx@gmail.com. Seis meses depois, você recebe spam nesse endereço exato. Agora você sabe que o ShoppingAppX:",
    "tempGmailPage.breachL1": "Vendeu seu email para marketeiros",
    "tempGmailPage.breachL2": "Teve um vazamento de dados",
    "tempGmailPage.breachL3": "Compartilha emails com \"parceiros\"",
    "tempGmailPage.breachP2": "Agora você pode criar um filtro do Gmail para excluir automaticamente tudo enviado para seunome+shoppingappx@gmail.com, bloqueando efetivamente essa fonte de spam sem afetar seus outros emails.",
    "tempGmailPage.filterTitle": "Como Configurar Filtros do Gmail para Plus-Addressing",
    "tempGmailPage.filterP1": "Assim que começar a usar plus-addressing, organize os emails recebidos automaticamente:",
    "tempGmailPage.filterL1": "Abrir Configurações do Gmail: Clique no ícone de engrenagem → \"Ver todas as configurações\"",
    "tempGmailPage.filterL2": "Ir para \"Filtros e endereços bloqueados\": Clique em \"Criar um novo filtro\"",
    "tempGmailPage.filterL3": "Adicionar Regra de Filtro: No campo \"Para\", digite seunome+compras@gmail.com",
    "tempGmailPage.filterL4": "Escolher Ação: Aplicar etiqueta \"Compras\", pular caixa de entrada, marcar como lido, encaminhar ou excluir",
    "tempGmailPage.filterL5": "Salvar Filtro: Clique em \"Criar filtro\" e pronto",
    "tempGmailPage.filterP2": "Agora cada email enviado para esse endereço é automaticamente organizado segundo suas regras.",
    "tempGmailPage.limitTitle": "Limitações das Funcionalidades Integradas do Gmail",
    "tempGmailPage.limitP1": "Embora poderosas, o plus-addressing e o truque do ponto do Gmail têm algumas limitações:",
    "tempGmailPage.limitL1": "Não é Verdadeiramente Anônimo: Seu endereço Gmail base ainda é visível. Qualquer pessoa pode remover a \"+etiqueta\" para encontrar seu endereço real.",
    "tempGmailPage.limitL2": "Alguns Sites Bloqueiam o Sinal +: Alguns sites rejeitam endereços de email contendo símbolos \"+\".",
    "tempGmailPage.limitL3": "Sem Proteção do Google: O Google ainda vê toda sua atividade. Esses truques não te protegem da coleta de dados do Google.",
    "tempGmailPage.limitL4": "Não é Possível Excluir Aliases Individuais: Diferente dos emails verdadeiramente descartáveis, você não pode \"queimar\" um alias se ele for comprometido.",
    "tempGmailPage.limitL5": "Não para Cadastros de Alto Risco: Como seu Gmail real ainda está tecnicamente exposto, não use esses truques para sites não confiáveis. Use Fire Temp Mail em vez disso.",
    "tempGmailPage.vsTitle": "Quando Usar Truques do Gmail vs. Emails Verdadeiramente Descartáveis",
    "tempGmailPage.useGmailTitle": "Use Plus-Addressing/Truque do Ponto do Gmail Quando:",
    "tempGmailPage.useGmailL1": "Você quiser que os emails cheguem na sua caixa principal",
    "tempGmailPage.useGmailL2": "Precisar rastrear quais serviços compartilham/vendem seu email",
    "tempGmailPage.useGmailL3": "Quiser organizar emails de diferentes fontes",
    "tempGmailPage.useGmailL4": "O serviço é relativamente confiável mas gera spam",
    "tempGmailPage.useGmailL5": "Você pode precisar de acesso a longo prazo à conta",
    "tempGmailPage.useDispTitle": "Use os Emails Totalmente Descartáveis do Fire Temp Mail Quando:",
    "tempGmailPage.useDispL1": "Precisar de anonimato completo (sem vínculo com seu email real)",
    "tempGmailPage.useDispL2": "Se cadastrar em sites não confiáveis ou arriscados",
    "tempGmailPage.useDispL3": "Verificações únicas que nunca mais vai precisar",
    "tempGmailPage.useDispL4": "Testes durante o desenvolvimento sem preencher sua caixa real",
    "tempGmailPage.useDispL5": "Serviços que podem gerar muito spam ou vender dados agressivamente",
    "tempGmailPage.tipsTitle": "Dicas de Privacidade e Técnicas Avançadas Específicas do Gmail",
    "tempGmailPage.tip1Title": "1. Criar um Sistema de Filtros \"Queimador\" no Gmail",
    "tempGmailPage.tip1P1": "Configure um filtro dedicado para todos os emails com plus-addressing:",
    "tempGmailPage.tip1L1": "Condição do filtro: to:seunome+*@gmail.com",
    "tempGmailPage.tip1L2": "Ação: Aplicar etiqueta \"Cadastros Rastreados\" e pular caixa de entrada",
    "tempGmailPage.tip1L3": "Resultado: Todos os emails com plus-addressing evitam sua caixa principal, mantendo-a limpa",
    "tempGmailPage.tip2Title": "2. Usar Convenções de Nomes Sistemáticas",
    "tempGmailPage.tip2P1": "Desenvolva um sistema de rotulagem consistente:",
    "tempGmailPage.tip2L1": "+compra-[nomesite] — Sites de compras",
    "tempGmailPage.tip2L2": "+news-[assunto] — Newsletters",
    "tempGmailPage.tip2L3": "+teste-[servico] — Testes gratuitos",
    "tempGmailPage.tip2L4": "+social-[plataforma] — Redes sociais",
    "tempGmailPage.tip3Title": "3. Rastrear Fontes de Vazamentos de Dados",
    "tempGmailPage.tip3P1": "Quando receber spam ou emails de phishing, verifique o campo \"Para\". Se mostrar seunome+siteespecifico@gmail.com, você identificou a fonte do vazamento ou violação de dados.",
    "tempGmailPage.ctaTitle": "Comece a Usar as Funções de Privacidade do Gmail Hoje",
    "tempGmailPage.ctaP1": "O plus-addressing e o truque do ponto do Gmail são funcionalidades totalmente gratuitas e integradas que funcionam agora mesmo com sua conta Gmail existente. Sem cadastro, sem serviço terceiro, sem risco. Comece a proteger sua privacidade e organizar sua caixa de entrada aproveitando essas poderosas capacidades específicas do Gmail.",
    "tempGmailPage.ctaP2": "Para situações que requerem anonimato completo: Use os endereços de email temporário verdadeiramente descartáveis do Fire Temp Mail na página principal. Para tudo o mais, use as funções de privacidade integradas do Gmail explicadas aqui.",
    "burnerEmailPage.h1": "Gerador de Email Queimador Grátis – Crie Endereços Descartáveis Instantaneamente",
    "burnerEmailPage.lead": "Gere endereços de email anônimos instantaneamente. Perfeitos para proteger sua identidade real online — sem cadastro, sem dados pessoais necessários.",
    "burnerEmailPage.seoTitle": "O Que É um Email Queimador e Por Que Você Precisa de Um?",
    "burnerEmailPage.seoP1": "Um email queimador é um endereço de email descartável e temporário que permite enviar ou receber mensagens sem revelar sua identidade real. Diferente de uma conta de email regular que você mantém por anos, um email queimador é deliberadamente de curta duração e anônimo — projetado para usar uma vez e depois descartar.",
    "burnerEmailPage.seoP2": "O termo \"queimador\" vem dos \"telefones queimadores\" — telefones pré-pagos e irrastreáveis usados para comunicação temporária. Os emails queimadores funcionam da mesma forma: criam uma camada de separação entre sua identidade real e o mundo online.",
    "burnerEmailPage.howTitle": "Como Funcionam os Emails Queimadores",
    "burnerEmailPage.howP1": "Serviços de email queimador como Fire Temp Mail geram um endereço de email aleatório no momento em que você visita o site. Não precisa criar conta, inserir informações pessoais ou verificar nada. Funciona assim:",
    "burnerEmailPage.howL1": "Geração Instantânea: Visite o site e receba um endereço de email aleatório e anônimo imediatamente.",
    "burnerEmailPage.howL2": "Receber Emails: Use o endereço para se cadastrar em serviços, receber códigos de verificação ou aceitar mensagens únicas.",
    "burnerEmailPage.howL3": "Sem Vínculo de Identidade: O endereço não tem conexão com seu nome real, número de telefone ou email permanente.",
    "burnerEmailPage.howL4": "Auto-Expiração: Após um curto período (geralmente 24 horas), o endereço de email e todas as mensagens associadas são excluídos permanentemente.",
    "burnerEmailPage.howL5": "Endereços Ilimitados: Gere quantos endereços queimadores precisar. Cada um é completamente independente.",
    "burnerEmailPage.usesTitle": "Principais Casos de Uso para Emails Queimadores",
    "burnerEmailPage.use1Title": "1. Cadastros e Inscrições em Sites",
    "burnerEmailPage.use1P": "A maioria dos sites exige um endereço de email para criar uma conta. Emails queimadores permitem se cadastrar sem arriscar sua caixa de entrada real ser inundada com emails promocionais e newsletters.",
    "burnerEmailPage.use2Title": "2. Cadastro em Testes Gratuitos",
    "burnerEmailPage.use2P": "Muitos serviços oferecem testes gratuitos por tempo limitado mas exigem um endereço de email. Use um email queimador para testar o serviço sem risco.",
    "burnerEmailPage.use3Title": "3. Compras Online e Cupons",
    "burnerEmailPage.use3P": "Sites de varejo frequentemente exigem um email para checkout ou para desbloquear descontos. Um email queimador previne spam pós-compra enquanto dá acesso às ofertas.",
    "burnerEmailPage.use4Title": "4. Login de Wi-Fi Público",
    "burnerEmailPage.use4P": "Cafeterias, aeroportos e hotéis frequentemente exigem um endereço de email para acessar suas redes Wi-Fi. Use um email queimador ao invés do seu email pessoal.",
    "burnerEmailPage.use5Title": "5. Download de Recursos",
    "burnerEmailPage.use5P": "E-books, whitepapers, templates e outros recursos para download geralmente estão atrás de um portão de email. Emails queimadores permitem acessar o conteúdo sem se inscrever em listas de email indesejadas.",
    "burnerEmailPage.use6Title": "6. Cadastros em Fóruns e Comunidades",
    "burnerEmailPage.use6P": "Fóruns, comunidades tipo Reddit e quadros de discussão frequentemente exigem emails para criar contas. Use um email queimador para participar anonimamente.",
    "burnerEmailPage.use7Title": "7. Testes de Desenvolvimento e QA",
    "burnerEmailPage.use7P": "Desenvolvedores de software e testadores constantemente precisam de endereços de email frescos para testar fluxos de cadastro, sistemas de verificação e funcionalidades de notificação.",
    "burnerEmailPage.benefitsTitle": "Benefícios de Usar Emails Queimadores",
    "burnerEmailPage.ben1": "Proteção de Privacidade: Seu email real permanece oculto. Ninguém pode rastrear um email queimador até você.",
    "burnerEmailPage.ben2": "Prevenção de Spam: Todo spam vai para o endereço queimador, mantendo sua caixa de entrada real limpa para sempre.",
    "burnerEmailPage.ben3": "Segurança contra Vazamentos: Se o serviço no qual você se cadastrou for hackeado, seu email real não estará na lista de usuários vazada.",
    "burnerEmailPage.ben4": "Sem Gerenciamento de Conta: Sem senhas para lembrar. Sem contas adicionais para manter.",
    "burnerEmailPage.ben5": "Instantâneo e Grátis: Sem cadastro necessário. Sem custo. Apenas visite, gere e use.",
    "burnerEmailPage.vsTitle": "Email Queimador vs. Email Regular vs. Alias de Email",
    "burnerEmailPage.vsP1": "Email Regular (Gmail, Outlook): Permanente, vinculado à sua identidade, usado para comunicação a longo prazo. Vulnerável ao spam e vazamentos de dados.",
    "burnerEmailPage.vsP2": "Alias de Email (+tags, pontos): Variações do seu email real que ainda são entregues na sua caixa de entrada. Úteis para organização mas não escondem seu endereço real.",
    "burnerEmailPage.vsP3": "Email Queimador (Fire Temp Mail): Completamente separado da sua identidade real. Temporário, anônimo, auto-exclusão. O melhor para privacidade e uso único.",
    "eduEmailPage.h1": "Gerador de Email EDU Grátis – Crie uma Caixa .EDU Descartável Instantaneamente",
    "eduEmailPage.lead": "Gere emails .EDU com nosso gerador de Email EDU gratuito. Perfeito para cadastros, testes, descontos estudantis e mais — sem expor sua caixa de entrada real ao spam.",
    "eduEmailPage.seoTitle": "Principais Descontos Estudantis e Benefícios de Email .EDU",
    "eduEmailPage.seoP1": "Descontos estudantis podem economizar milhares de dólares por ano em software, serviços de streaming e recursos de aprendizado.",
    "eduEmailPage.discountsTitle": "Principais Descontos Estudantis que Requerem Verificação .EDU",
    "eduEmailPage.spotifyTitle": "Spotify Premium Estudante - $5,99/mês (50% de desconto)",
    "eduEmailPage.spotifyP1": "Preço Regular: $10,99/mês | Economia Estudantil: $60/ano",
    "eduEmailPage.spotifyP2": "Inclui Hulu (com anúncios) e SHOWTIME sem custo adicional. Verificado via SheerID com seu email .EDU.",
    "eduEmailPage.amazonTitle": "Amazon Prime Student - $7,49/mês",
    "eduEmailPage.amazonP1": "Preço Regular: $14,99/mês | Economia Estudantil: $90/ano + teste GRÁTIS de 6 meses",
    "eduEmailPage.amazonP2": "Todos os benefícios Prime: Frete grátis em 2 dias, Prime Video, Prime Music, armazenamento ilimitado de fotos e mais.",
    "eduEmailPage.adobeTitle": "Adobe Creative Cloud - 60% de desconto",
    "eduEmailPage.adobeP1": "Preço Regular: $59,99/mês | Preço Estudante: $19,99/mês | Economia: $480/ano",
    "eduEmailPage.adobeP2": "Suite completa: Photoshop, Illustrator, Premiere Pro, After Effects, InDesign e mais de 20 aplicativos.",
    "eduEmailPage.appleTitle": "Apple Music Estudante - $5,99/mês",
    "eduEmailPage.appleP1": "Preço Regular: $10,99/mês | Economia Estudantil: $60/ano",
    "eduEmailPage.appleP2": "Catálogo completo do Apple Music mais assinatura gratuita do Apple TV+ incluída.",
    "eduEmailPage.githubTitle": "GitHub Student Developer Pack - GRÁTIS",
    "eduEmailPage.githubP1": "Custo Normal: $200+/ano em ferramentas | Preço Estudante: Completamente GRÁTIS",
    "eduEmailPage.githubP2": "GitHub Pro, nome de domínio grátis, créditos na nuvem, ferramentas CI/CD e mais de 20 ferramentas e serviços para desenvolvedores.",
    "bestTempMailPage.h1": "Melhor Temp Mail – Serviço #1 de Email Temporário Descartável Grátis",
    "bestTempMailPage.lead": "O melhor serviço de correio temporário online. Gere endereços de email descartáveis instantâneos — sem cadastro, sem informações pessoais necessárias. Privado, rápido e grátis.",
    "bestTempMailPage.seoTitle": "Por Que Fire Temp Mail é o Melhor Serviço de Email Temporário",
    "bestTempMailPage.seoP1": "Com dezenas de serviços de email temporário disponíveis online, escolher o certo importa. Fire Temp Mail se destaca como o melhor serviço de temp mail por várias razões chave.",
    "bestTempMailPage.comparison": "Comparação de Funcionalidades com Outros Serviços",
    "bestTempMailPage.whyBestTitle": "O Que Nos Torna os Melhores",
    "bestTempMailPage.whyBestP1": "Fire Temp Mail combina velocidade, privacidade e simplicidade de uma forma que nenhum outro serviço de email temporário oferece.",
    "bestTempMailPage.feature1": "Geração Instantânea: Sem espera, sem cadastro. Visite a página e seu email temporário está pronto imediatamente.",
    "bestTempMailPage.feature2": "Múltiplos Domínios: Escolha entre vários domínios de email diferentes para atender suas necessidades.",
    "bestTempMailPage.feature3": "Endereços Estilo Gmail: Obtenha endereços temporários tipo Gmail que funcionam em todos os lugares.",
    "bestTempMailPage.feature4": "Aliases Personalizados: Crie endereços temporários personalizados para organização.",
    "bestTempMailPage.feature5": "Caixa Auto-Atualizada: Novos emails aparecem automaticamente sem atualização manual.",
    "bestTempMailPage.feature6": "Privacidade Primeiro: Sem rastreamento, sem registro, sem coleta de dados.",
    "gmailGeneratorPage.h1": "Gerador Gmail Grátis – Crie Endereços Gmail Temporários Instantaneamente",
    "gmailGeneratorPage.lead": "Gere um endereço Gmail temporário grátis com nosso Gerador Gmail. Acesse uma caixa Gmail descartável instantaneamente — sem cadastro, sem dados pessoais. Mantenha-se anônimo online.",
    "gmailGeneratorPage.seoTitle": "Como o Gerador Gmail Funciona",
    "gmailGeneratorPage.seoP1": "Nosso Gerador Gmail cria endereços descartáveis estilo Gmail que funcionam como contas Gmail reais. Use-os para cadastros, verificações e testes sem expor seu endereço Gmail real.",
    "gmailGeneratorPage.howItWorksTitle": "Como Funciona",
    "gmailGeneratorPage.howItWorksP1": "1. Visite Fire Temp Mail e selecione a opção Gmail. 2. Um endereço temporário estilo Gmail é gerado instantaneamente. 3. Use-o para qualquer cadastro ou verificação online. 4. Receba emails em tempo real na sua caixa privada. 5. O endereço expira automaticamente após 24 horas.",
    "temporaryGmailPage.h1": "Gmail Temporário – Endereços Gmail Descartáveis Grátis",
    "temporaryGmailPage.lead": "Obtenha um endereço Gmail temporário grátis que funciona exatamente como uma conta Gmail real. Perfeito para cadastros, verificações e proteção da sua caixa principal contra spam.",
    "temporaryGmailPage.seoTitle": "Endereços Gmail Temporários Explicados",
    "temporaryGmailPage.seoP1": "Um endereço Gmail temporário é um email descartável de curta duração que parece e funciona como uma conta Gmail real. Permite receber emails de verificação, cadastrar-se em serviços e manter a privacidade sem expor seu email permanente.",
    "temporaryGmailPage.benefitsTitle": "Benefícios do Gmail Temporário",
    "temporaryGmailPage.benefitsP1": "Proteja seu Gmail real do spam, evite vazamentos de dados e cadastre-se em serviços anonimamente. Tudo sem cadastro necessário.",
    "tempMailEduPage.h1": "Temp Mail EDU – Gerador de Email .EDU Temporário Grátis",
    "tempMailEduPage.lead": "Gere endereços de email .EDU temporários instantaneamente. Acesse descontos estudantis, recursos educacionais e ferramentas online com uma caixa .EDU descartável.",
    "tempMailEduPage.seoTitle": "Usando Temp Mail para Propósitos Educacionais",
    "tempMailEduPage.seoP1": "Emails .EDU temporários podem ajudar a acessar recursos educacionais, testar sistemas de verificação estudantil e explorar funcionalidades de plataformas projetadas para a comunidade acadêmica.",
    "tenMinuteMailPage.h1": "10 Minute Mail – Email Descartável Rápido que Expira Rápido",
    "tenMinuteMailPage.lead": "Precisa de um email rápido e descartável? Nosso 10 Minute Mail dá um endereço descartável instantâneo que se auto-exclui. Perfeito para cadastros e verificações únicas.",
    "tenMinuteMailPage.seoTitle": "O Que é 10 Minute Mail e Como Funciona?",
    "tenMinuteMailPage.seoP1": "10 Minute Mail é um tipo de serviço de email descartável que fornece um endereço de email temporário que dura apenas 10 minutos. É a forma mais rápida de obter um email descartável para cadastros e verificações rápidas.",
    "tenMinuteMailPage.howTitle": "Como o 10 Minute Mail Funciona",
    "tenMinuteMailPage.howP1": "Visite a página e obtenha um endereço de email instantâneo. Use-o para qualquer cadastro ou verificação. O endereço e todos os emails são excluídos permanentemente após 10 minutos.",
    "tenMinuteMailPage.whyTitle": "Por Que Usar 10 Minute Mail?",
    "tenMinuteMailPage.whyP1": "Às vezes você não precisa de um endereço de email por muito tempo. Cadastros rápidos, verificações únicas e download de conteúdo protegido são todos casos de uso perfeitos para 10 minute mail.",
    "tenMinuteMailPage.vsTitle": "10 Minute Mail vs Temp Mail Regular",
    "tenMinuteMailPage.vsP1": "10 Minute Mail é mais rápido e projetado para casos de uso ultra-rápidos. O email temporário regular (como Fire Temp Mail) dura mais (até 24 horas) e é melhor para testes, desenvolvimento e situações onde você precisa do email por mais de alguns minutos.",
    "temporaryEmailGenPage.h1": "Gerador de Email Temporário – Crie Endereços de Email Descartáveis Grátis",
    "temporaryEmailGenPage.lead": "Gere endereços de email temporários instantaneamente. Nosso Gerador de Email Temporário fornece caixas descartáveis gratuitas — perfeitas para proteger sua privacidade online.",
    "temporaryEmailGenPage.seoTitle": "Como Funcionam os Geradores de Email Temporário",
    "temporaryEmailGenPage.seoP1": "Um gerador de email temporário cria endereços de email anônimos de curta duração sob demanda. Esses endereços funcionam como emails regulares mas expiram automaticamente, mantendo sua identidade real protegida.",
    "fireMailPage.h1": "Fire Mail – Serviço de Email Temporário Rápido e Grátis",
    "fireMailPage.lead": "Fire Mail fornece endereços de email temporários instantâneos para privacidade online completa. Sem cadastro, sem dados pessoais — apenas email descartável puro e criptografado.",
    "fireMailPage.seoTitle": "Por Que Escolher Fire Mail para Email Temporário",
    "fireMailPage.seoP1": "Fire Mail é construído para velocidade, privacidade e confiabilidade. Nosso serviço de email temporário gera endereços descartáveis instantaneamente, com atualizações de caixa de entrada em tempo real e limpeza automática.",
    "gmailnatorPage.h1": "Alternativa ao Gmailnator – Gerador Gmail Temporário Grátis",
    "gmailnatorPage.lead": "Procurando uma alternativa ao Gmailnator? Fire Temp Mail oferece a mesma funcionalidade com melhor privacidade, desempenho mais rápido e entrega de email mais confiável.",
    "gmailnatorPage.seoTitle": "Melhor Alternativa ao Gmailnator em 2024",
    "gmailnatorPage.seoP1": "Gmailnator era um serviço popular para gerar endereços Gmail temporários. Fire Temp Mail oferece a mesma funcionalidade com confiabilidade melhorada, melhores proteções de privacidade e uma experiência de usuário moderna.",
    "about.metaTitle": "Sobre Fire Temp Mail - Nossa Missão e História",
    "about.metaDescription": "Conheça Fire Temp Mail — um serviço de email temporário gratuito que protege sua privacidade online. Nossa missão e valores.",
    "about.title": "Sobre Fire Temp Mail",
    "about.subtitle": "Protegendo sua privacidade digital, um email temporário de cada vez",
    "about.missionTitle": "Nossa Missão",
    "about.missionP1": "Fire Temp Mail foi criado para resolver um problema simples mas crítico: a erosão da privacidade online. Todos os dias, milhões de pessoas são forçadas a fornecer seus endereços de email pessoais para acessar serviços, se cadastrar em testes ou baixar recursos — frequentemente resultando em uma caixa de entrada inundada de spam e emails de marketing indesejados.",
    "about.missionP2": "Acreditamos que seu endereço de email é pessoal. Você não deveria ter que sacrificar sua privacidade ou comprometer a segurança da sua caixa de entrada só para acessar serviços online. Por isso construímos Fire Temp Mail: um serviço de email temporário completamente gratuito e sem cadastro que prioriza sua privacidade.",
    "about.whatWeDoTitle": "O Que Fazemos",
    "about.whatWeDoP1": "Fire Temp Mail fornece endereços de email instantâneos, anônimos e descartáveis que qualquer pessoa pode usar — sem cadastro necessário. Seja para um email temporário para um cadastro único, evitar spam de newsletters ou proteger sua identidade real online, nós resolvemos.",
    "about.whatWeDo1": "Geração instantânea de email — apenas visite e obtenha um endereço de email funcional",
    "about.whatWeDo2": "Caixa de entrada em tempo real — receba emails instantaneamente no seu navegador",
    "about.whatWeDo3": "Múltiplos domínios — escolha entre vários domínios de email disponíveis",
    "about.whatWeDo4": "Aliases personalizados — crie endereços temporários personalizados",
    "about.whatWeDo5": "Endereços estilo Gmail — obtenha endereços temporários tipo Gmail",
    "about.whatWeDo6": "Auto-exclusão — os emails são automaticamente limpos para total privacidade",
    "about.whyTitle": "Por Que Fire Temp Mail?",
    "about.whyP1": "Em um mundo onde vazamentos de dados, spam e marketing não solicitado são problemas cotidianos, Fire Temp Mail oferece uma solução simples mas poderosa.",
    "about.why1": "Grátis para sempre — sem custos ocultos, assinaturas ou restrições premium",
    "about.why2": "Sem cadastro — comece a usar instantaneamente, sem conta necessária",
    "about.why3": "Privacidade primeiro — não rastreamos, vendemos ou monetizamos seus dados",
    "about.why4": "Aberto e transparente — serviço direto sem truques",
    "about.why5": "Rápido e confiável — construído em infraestrutura moderna para velocidade",
    "about.valuesTitle": "Nossos Valores",
    "about.value1Title": "Privacidade Acima de Tudo",
    "about.value1Text": "Acreditamos que a privacidade é um direito fundamental. Nosso serviço é projetado desde o início para proteger a sua.",
    "about.value2Title": "Simplicidade",
    "about.value2Text": "Obter um email temporário deve ser fácil. Visite nosso site, pegue um email, use. É isso.",
    "about.value3Title": "Transparência",
    "about.value3Text": "Sem agendas ocultas. Somos diretos sobre como nosso serviço funciona e como o sustentamos.",
    "about.value4Title": "Acessibilidade",
    "about.value4Text": "Todos merecem privacidade. Por isso Fire Temp Mail é grátis para todos, em todos os lugares.",
    "about.futureTitle": "Olhando para o Futuro",
    "about.futureP1": "Estamos constantemente melhorando Fire Temp Mail para servir melhor nossos usuários. Nosso roteiro inclui funcionalidades de segurança aprimoradas, mais opções de domínio, experiência móvel melhorada e ferramentas adicionais para proteger sua privacidade digital.",
    "about.futureP2": "Obrigado por confiar no Fire Temp Mail com sua privacidade online. Juntos, estamos construindo uma internet mais segura e privada — um email temporário de cada vez.",
    "about.contactTitle": "Entre em Contato",
    "about.contactP1": "Tem perguntas, feedback ou quer apenas dizer olá? Adoraríamos ouvir de você.",
    "about.contactEmail": "Envie um email para",
    "about.contactLink": "Ou visite nossa página de Contato"
}

for dotpath, value in t.items():
    set_nested(locale, dotpath, value)

with open(os.path.join(BASE, 'pt.json'), 'w') as f:
    json.dump(locale, f, indent=2, ensure_ascii=False)
print(f"Updated pt.json with {len(t)} new keys")
