name = "firetempmail-frontend"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-01-29"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "BLOG_DB"
database_name = "blog-db"
database_id = "7dac6c8a-ff23-4317-862d-2c6073afab8e"