// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/*",
    "/assets/blog/adobe-entered-temp-email.svg",
    "/assets/blog/adobe-inbox-temp-email.svg",
    "/assets/blog/adobe-signup-temp-email.svg",
    "/assets/blog/adobe-success-temp-email.svg",
    "/assets/blog/aliexpress-entered-temp-email.svg",
    "/assets/blog/aliexpress-inbox-temp-email.svg",
    "/assets/blog/aliexpress-signup-temp-email.svg",
    "/assets/blog/aliexpress-success-temp-email.svg",
    "/assets/blog/beginner-copy-email-address.svg",
    "/assets/blog/beginner-email-routing-diagram.svg",
    "/assets/blog/beginner-firetempmail-homepage.svg",
    "/assets/blog/beginner-inbox-email-arrives.svg",
    "/assets/blog/beginner-read-verification-code.svg",
    "/assets/blog/canva-entered-temp-email.svg",
    "/assets/blog/canva-inbox-temp-email.svg",
    "/assets/blog/canva-signup-temp-email.svg",
    "/assets/blog/canva-success-temp-email.svg",
    "/assets/blog/chatgpt-account-result.svg",
    "/assets/blog/chatgpt-signup-page.svg",
    "/assets/blog/chatgpt-temp-email-entered.svg",
    "/assets/blog/chatgpt-verification-inbox.svg",
    "/assets/blog/claude-ai-signup-page.svg",
    "/assets/blog/claude-temp-email-entered.svg",
    "/assets/blog/claude-temp-email-result.svg",
    "/assets/blog/cursor-entered-temp-email.svg",
    "/assets/blog/cursor-inbox-temp-email.svg",
    "/assets/blog/cursor-signup-temp-email.svg",
    "/assets/blog/cursor-success-temp-email.svg",
    "/assets/blog/deepseek-temp-email.svg",
    "/assets/blog/developer-temp-email-testing.svg",
    "/assets/blog/discord-account-created.svg",
    "/assets/blog/discord-temp-email-signup.svg",
    "/assets/blog/discord-verification-inbox.svg",
    "/assets/blog/firetempmail-claude-verification-inbox.svg",
    "/assets/blog/freepik-account-download-page.svg",
    "/assets/blog/freepik-email-verification.svg",
    "/assets/blog/freepik-entered-temp-email.svg",
    "/assets/blog/freepik-inbox-temp-email.svg",
    "/assets/blog/freepik-signup-temp-email.svg",
    "/assets/blog/freepik-success-temp-email.svg",
    "/assets/blog/gemini-google-temp-email.svg",
    "/assets/blog/grok-x-temp-email.svg",
    "/assets/blog/heygen-temp-email-signup.svg",
    "/assets/blog/instagram-account-active.svg",
    "/assets/blog/instagram-signup-form.svg",
    "/assets/blog/instagram-temp-email-entered.svg",
    "/assets/blog/instagram-verification-inbox.svg",
    "/assets/blog/kick-entered-temp-email.svg",
    "/assets/blog/kick-inbox-temp-email.svg",
    "/assets/blog/kick-signup-temp-email.svg",
    "/assets/blog/kick-success-temp-email.svg",
    "/assets/blog/kling-temp-email-signup.svg",
    "/assets/blog/notion-entered-temp-email.svg",
    "/assets/blog/notion-inbox-temp-email.svg",
    "/assets/blog/notion-signup-temp-email.svg",
    "/assets/blog/notion-success-temp-email.svg",
    "/assets/blog/openrouter-temp-email.svg",
    "/assets/blog/pinterest-entered-temp-email.svg",
    "/assets/blog/pinterest-inbox-temp-email.svg",
    "/assets/blog/pinterest-signup-temp-email.svg",
    "/assets/blog/pinterest-success-temp-email.svg",
    "/assets/blog/privacy-email-tiers-diagram.svg",
    "/assets/blog/protonvpn-temp-email.svg",
    "/assets/blog/reddit-entered-temp-email.svg",
    "/assets/blog/reddit-inbox-temp-email.svg",
    "/assets/blog/reddit-signup-temp-email.svg",
    "/assets/blog/reddit-success-temp-email.svg",
    "/assets/blog/runway-free-credits.svg",
    "/assets/blog/runway-temp-email-signup.svg",
    "/assets/blog/spotify-entered-temp-email.svg",
    "/assets/blog/spotify-inbox-temp-email.svg",
    "/assets/blog/spotify-signup-temp-email.svg",
    "/assets/blog/spotify-success-temp-email.svg",
    "/assets/blog/steam-temp-email-signup.svg",
    "/assets/blog/tiktok-account-created.svg",
    "/assets/blog/tiktok-signup-email.svg",
    "/assets/blog/tiktok-temp-email-entered.svg",
    "/assets/blog/tiktok-verification-code.svg",
    "/assets/blog/tumblr-entered-temp-email.svg",
    "/assets/blog/tumblr-inbox-temp-email.svg",
    "/assets/blog/tumblr-signup-temp-email.svg",
    "/assets/blog/tumblr-success-temp-email.svg",
    "/assets/blog/windscribe-temp-email.svg",
    "/assets/bootstrap/css/bootstrap.min.css",
    "/assets/bootstrap/js/bootstrap.min.js",
    "/assets/img/android-chrome-192x192.png",
    "/assets/img/android-chrome-512x512.png",
    "/assets/img/apple-touch-icon.png",
    "/assets/img/favicon-16x16.png",
    "/assets/img/favicon-32x32.png",
    "/assets/img/ring-resize.svg",
    "/assets/js/jquery.min.js",
    "/favicon.ico",
    "/favicon.png",
    "/header.css",
    "/header.min.css",
    "/logo.svg",
    "/offers.json"
  ]
};

// node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "/Users/badr/Desktop/firetempmail/frontend/.wrangler/tmp/pages-pUvb2n/bundledWorker-0.4823830273581595.mjs";
import { isRoutingRuleMatch } from "/Users/badr/Desktop/firetempmail/frontend/node_modules/wrangler/templates/pages-dev-util.ts";
export * from "/Users/badr/Desktop/firetempmail/frontend/.wrangler/tmp/pages-pUvb2n/bundledWorker-0.4823830273581595.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        const workerAsHandler = worker;
        if (workerAsHandler.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return workerAsHandler.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=youwki87pt.js.map
